// The TypeScript types for the API's published schema, and the one writer of how they are made
// (ADR 0032). `src/api/schema.gen.ts` is this module's output for `openapi.json`, the committed
// snapshot `scripts/openapi_snapshot.py` writes from the live app.
//
// Two callers: `scripts/refresh-api-types.mjs` (run by `npm run api:refresh`) writes the file,
// and `scripts/api-types.test.ts` asserts the committed file is byte-for-byte what `generate`
// makes from the committed snapshot - so a hand edit, or a snapshot refreshed without its types,
// fails the client's test run.
import openapiTS, { astToString } from 'openapi-typescript';

export const SNAPSHOT_URL = new URL('../openapi.json', import.meta.url);
export const GENERATED_URL = new URL('../src/api/schema.gen.ts', import.meta.url);

const HEADER = [
  '// This file is generated by `npm run api:refresh` from web/openapi.json, the snapshot of the',
  "// API's published schema. Change the API's models and refresh: a hand edit here fails",
  '// scripts/api-types.test.ts. Only the SUCCESS side is trustworthy - the schema advertises',
  "// FastAPI's default 422 body, which the API never sends (see src/api/envelope.ts).",
  '',
  '',
].join('\n');

/**
 * The generated module's full text for one snapshot.
 * @param {string} snapshotText the contents of `openapi.json`
 * @returns {Promise<string>}
 */
export async function generate(snapshotText) {
  // A string is read as a JSON (or YAML) document, not as a path: openapi-typescript treats only
  // a string that starts with a URL scheme as a location.
  const ast = await openapiTS(snapshotText);
  return HEADER + astToString(ast);
}
