const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
class Element {
  constructor(tag = 'div') { this.tagName = tag; this.children = []; this.listeners = {}; this.value = ''; this.disabled = false; this.hidden = false; this.textContent = ''; this.className = ''; this.attributes = {}; this.classList = {toggle: (name, value) => {const set = new Set(this.className.split(' ').filter(Boolean)); if (value) set.add(name); else set.delete(name); this.className = [...set].join(' ');}}; }
  append(...nodes) { this.children.push(...nodes); }
  replaceChildren(...nodes) { this.children = [...nodes]; }
  addEventListener(type, fn) { this.listeners[type] = fn; }
  setAttribute(k,v) {this.attributes[k] = v;}
  fire(type) { return this.listeners[type]?.({target:this}); }
}
const root = require('path').join(__dirname, '../renderer/');
const html = fs.readFileSync(root + 'index.html', 'utf8');
const source = fs.readFileSync(root + 'app.js', 'utf8');
const nodes = Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m => [m[1],new Element()]));
let emit, pendingAskResolve, payload, initResolve, libraryCall;
let current = {session: {status:'disconnected',sharing:false}, models:[]};
const gct = {onState(fn) {emit=fn; return ()=>{};}, getState:()=>new Promise(r=>initResolve=r), async signIn(...args){assert.equal(args.length,0,'sign-in must use no-argument IPC');return current;}, async cancelSignIn(){return current;}, async signOut(){return current;}, async chooseFile(){return current;}, async useSample(){return current;}, async cancelAsk(){current={...current,busy:null,result:{state:'CANCELLED'}};emit(current);return current;}, async openUsage(){return current;}, ask(p){payload=p;current={...current,busy:'ask',result:undefined};emit(current);return new Promise(r=>pendingAskResolve=r);}};
for (const name of ['createClass','selectClass','selectStoredDocument','deleteDocument','deleteClass','backupLibrary','showCitation']) gct[name] = async value => { libraryCall = {name,value}; return current; };
vm.runInNewContext(source, {document:{getElementById:id=>nodes[id],createElement:tag=>new Element(tag)},window:{gct,addEventListener(){}},console,Promise,Set,Map,JSON});
const flush=()=>new Promise(r=>setImmediate(r));
const update=(changes)=>{current={...current,...changes};emit(structuredClone(current));};
(async()=>{
  await flush();
  nodes['sign-in'].fire('click');await flush();
  assert.equal(nodes.ask.disabled,true,'disconnected must not ask');
  update({session:{status:'connected',sharing:true,identity:{name:'Student <img>'}},models:[{slug:'m1',display_name:'Model one'},{slug:'m2',display_name:'Model two'}],document:{filename:'<img src=x>.pdf',page_count:6,pages:Array.from({length:6},(_,i)=>({page_or_slide:i+1,text:'Source <script> '+i}))}});
  assert.equal(nodes['account-identity'].textContent,'Student <img>');
  assert.equal(nodes['document-name'].textContent,'<img src=x>.pdf');
  assert.equal(nodes['selection-count'].textContent,'5 of 5 selected');
  const rows=nodes['page-options'].children.slice(1);
  assert.equal(rows[5].children[0].disabled,true,'sixth page must be disabled');
  rows[0].children[0].checked=false;rows[0].children[0].fire('change');
  assert.equal(rows[5].children[0].disabled,false,'sixth unlocked when selection below five');
  rows[5].children[0].checked=true;rows[5].children[0].fire('change');
  nodes.question.value=' What is the idea? ';nodes.question.fire('input');
  assert.equal(nodes.ask.disabled,false);
  nodes.model.value='m2';nodes.model.fire('change');
  update({notice:'Connected'});
  assert.equal(nodes.model.value,'m2','valid selection survives fresh state');
  update({models:[{slug:'m1',display_name:'Model one'}]});
  assert.equal(nodes.model.value,'m1','removed model cannot remain selected');
  update({busy:'document'});
  for(const id of ['choose-file','use-sample','ask','sign-out','model','question'])assert.equal(nodes[id].disabled,true,id+' locked while parsing');
  assert.equal(nodes['ask-help'].textContent,'Reading document…');
  update({busy:null,session:{status:'connected',sharing:false}});
  assert.equal(nodes.ask.disabled,true,'sharing must be explicitly enabled');
  assert.equal(nodes['sign-in'].hidden,false,'connected identity must still be able to authorize plan use');
  update({session:{status:'connecting',sharing:false},busy:'signin'});
  assert.equal(nodes['cancel-sign-in'].hidden,false);
  assert.equal(nodes['sign-in'].disabled,true);
  update({session:{status:'connected',sharing:true},busy:null});
  nodes.ask.fire('click');await flush();
  assert.equal(payload.question,'What is the idea?');
  assert.deepEqual([...payload.pages],[2,3,4,5,6]);
  assert.equal(payload.model,'m1');
  assert.equal(nodes['answer-progress'].hidden,false);
  assert.equal(nodes['cancel-ask'].hidden,false);
  const grounded={state:'GROUNDED',answer_prose:'Safe <img onerror=x> answer.',citations:[{label:'[1]',file:'Example.pdf',page_or_slide:2,chunk_id:'x'}],coverage:{complete:true,gaps:[]},integrity:{ok:true,reasons:[]}};
  update({busy:null,result:grounded});pendingAskResolve(current);await flush();
  assert.equal(nodes['answer-content'].hidden,false);
  assert.equal(nodes['answer-badge'].textContent,'Grounded answer');
  assert.equal(nodes['answer-prose'].children[0].textContent,'Safe <img onerror=x> answer.');
  assert.equal(nodes.citations.children.length,1);
  nodes.question.value='Changed question';nodes.question.fire('input');
  assert.equal(nodes['answer-content'].hidden,true);
  update({notice:'Unrelated update'});
  assert.equal(nodes['answer-content'].hidden,true,'old answer stays hidden across cloned state');
  update({result:{...grounded,state:'PARTIAL',coverage:{complete:false,gaps:['Missing detail']}}});
  assert.equal(nodes['answer-badge'].textContent,'Partial support');assert.equal(nodes['gaps-section'].hidden,false);
  update({result:{...grounded,state:'INTEGRITY_FLAGGED',integrity:{ok:false,reasons:['Check source']}}});
  assert.equal(nodes['answer-badge'].textContent,'Needs review');assert.match(nodes['answer-alert'].textContent,/Check source/);
  update({result:{...grounded,state:'REFUSAL',answer_prose:'Insufficient material',coverage:{complete:false,gaps:[]}}});
  assert.equal(nodes['answer-badge'].textContent,'Not supported');
  update({result:{state:'ERROR',error:{message:'Please reconnect'}}});
  assert.equal(nodes['answer-badge'].textContent,'Couldn’t complete');assert.equal(nodes['answer-prose'].children.length,0);
  update({result:undefined});assert.equal(nodes['answer-content'].hidden,true);assert.equal(nodes['answer-empty'].hidden,false);
  initResolve({session:{status:'disconnected',sharing:false},models:[]});await flush();
  assert.equal(nodes['account-status-text'].textContent,'Connected','late initial snapshot must not overwrite streamed state');
  update({library:{classes:[{id:'class-a',name:'Systems <script>'}],selectedClassId:'class-a',documents:[{id:'document-a',filename:'Notes.pdf',page_count:2},{id:'document-b',filename:'Notes.pdf',page_count:2}],selectedDocumentId:null},document:undefined,result:undefined});
  assert.equal(nodes['class-picker'].children[1].textContent,'Systems <script>');
  assert.notEqual(nodes['document-picker'].children[1].textContent,nodes['document-picker'].children[2].textContent,'duplicate names must remain distinguishable');
  assert.equal(nodes['search-scope'].value,'class');
  nodes['class-picker'].value='';nodes['class-picker'].fire('change');
  assert.equal(nodes['class-picker'].value,'class-a','placeholder cannot misrepresent the active class');
  assert.equal(nodes.ask.disabled,false,'class search can ask without an open document');
  nodes.ask.fire('click');await flush();
  assert.equal(payload.scope,'class');assert.equal(payload.pages,undefined,'class search must not silently use selected pages');
  update({busy:null,result:grounded});pendingAskResolve(current);await flush();
  const sourceButton=nodes.citations.children[0].children[2];sourceButton.fire('click');await flush();
  assert.equal(libraryCall.name,'showCitation');assert.equal(libraryCall.value.chunkId,'x');
  update({citation:{document_id:'document-b',filename:'Notes.pdf',page_or_slide:2,text:'Exact saved <script> passage'}});
  assert.equal(nodes['citation-preview'].hidden,false);assert.equal(nodes['citation-text'].textContent,'Exact saved <script> passage');
  nodes.question.value='Another question';nodes.question.fire('input');
  assert.equal(nodes['citation-preview'].hidden,true,'question changes hide stale cited material');
  update({result:{...grounded,answer_prose:'A fresh answer'}});
  assert.equal(nodes['citation-preview'].hidden,false);
  nodes.model.fire('change');assert.equal(nodes['citation-preview'].hidden,true,'model changes hide stale cited material');
  nodes['search-scope'].value='document';nodes['search-scope'].fire('change');
  assert.equal(nodes.ask.disabled,true,'document mode requires an opened document');
  assert.equal(nodes['citation-preview'].hidden,true,'scope changes hide old citation previews');
  update({document:{id:'document-b',filename:'Notes.pdf',page_count:2,pages:[{page_or_slide:1,text:'a'},{page_or_slide:2,text:'b'}]},library:{...current.library,selectedDocumentId:'document-b'}});
  assert.equal(nodes.ask.disabled,false);
  assert.equal(nodes['page-section'].hidden,true,'page selections cannot imply restricted context during document search');
  nodes['document-picker'].value='';nodes['document-picker'].fire('change');
  assert.equal(nodes['document-picker'].value,'document-b');
  nodes.ask.fire('click');await flush();assert.equal(payload.scope,'document');assert.equal(payload.pages,undefined);
  update({busy:null,result:undefined});pendingAskResolve(current);await flush();
  nodes['search-scope'].value='pages';nodes['search-scope'].fire('change');
  assert.equal(nodes['page-section'].hidden,false);
  update({result:grounded});
  const savedRows=nodes['page-options'].children.slice(1);
  savedRows[0].children[0].checked=false;savedRows[0].children[0].fire('change');
  assert.equal(nodes['citation-preview'].hidden,true,'page changes hide stale cited material');
  savedRows[0].children[0].checked=true;savedRows[0].children[0].fire('change');
  nodes.ask.fire('click');await flush();assert.equal(payload.scope,'pages');assert.deepEqual([...payload.pages],[1,2]);
  update({busy:null,result:undefined});pendingAskResolve(current);await flush();
  update({session:{status:'disconnected',sharing:false}});
  assert.equal(nodes['choose-file'].disabled,false,'import works without a model account');
  assert.equal(nodes['backup-library'].disabled,false,'backup works without a model account');
  assert.equal(nodes.ask.disabled,true);
  nodes['class-name'].value='Algorithms';nodes['class-name'].fire('input');
  nodes['create-class'].fire('click');await flush();assert.equal(libraryCall.name,'createClass');assert.equal(libraryCall.value.name,'Algorithms');
  update({busy:'library'});
  for (const id of ['class-picker','document-picker','create-class','delete-document','delete-class','backup-library','search-scope']) assert.equal(nodes[id].disabled,true,id+' locked during mutation');
  assert(!source.includes('innerHTML'));
  assert(html.includes("connect-src 'none'"));
  assert(html.includes("default-src 'none'"));
  console.log('PASS: renderer account, busy, five-page bound, model refresh, safe text, stale-result, answer states, and initial-state race checks');
})().catch(err=>{console.error(err);process.exitCode=1});
