"""Tests for `scripts/ask_smoke.py` - the Slice 1 exit runner (issue #8, PR #44 review).

WHY A SCRIPT HAS TESTS AT ALL. ADR 0009 calls the scripts thin peer callers, and thin callers
usually earn none. This one is hundreds of lines and carries real branching that nothing else
covers:
corpus convergence, the duplicate-ingest WARN, the duplicate-class refusal, the setup-validity
guards, and the exit gate. Every defect found in PR #44's review lived in this file, and none of
them was visible from reading it - each needed the script RUN. The objection that running it costs
money is answered here: three independent reviewers each built a stub-provider harness to review
it, so the offline path plainly exists. This file is that harness, kept.

Everything here is OFFLINE and free - the real local Postgres (`db`), a fake embedder, and real
PDFs generated by reportlab. No `live` mark, no API key, nothing paid. Most tests stop before the
question loop; `TestMainWiring` runs the loop itself with `ask`, `connect` and both provider
classes monkeypatched to fakes, so no real provider is ever constructed and nothing can reach a
network call.

Every test taking `db` is automatically `db`-marked (tests/conftest.py derives it from the
fixture). A SKIP here locally means Postgres is down - it is not a pass.
"""

from __future__ import annotations

import dataclasses
import importlib.util
import io
import uuid
from pathlib import Path

import pytest
from reportlab.pdfgen import canvas

from gct.config import EMBEDDING_DIM
from gct.eval.questions import EvalQuestion, ExpectedSource
from gct.ingest.pipeline import ingest_file

# Import the script by PATH rather than by package name: `scripts/` is deliberately not a package
# (ADR 0009 - the scripts are peers of the library, not part of it), so there is nothing to
# `import`. Loading the file directly keeps that boundary intact instead of bending sys.path.
_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "ask_smoke.py"
_spec = importlib.util.spec_from_file_location("ask_smoke_under_test", _SCRIPT)
ask_smoke = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ask_smoke)


class FakeEmbeddings:
    """Deterministic, free, and LOUD if a test embeds when it should not have.

    `calls` is the assertion surface for convergence: the whole point of checking before ingesting
    is that a second run costs nothing, and the only way to prove "nothing" is that the embedder
    was never touched.
    """

    model_id = "fake-embed-3"

    def __init__(self) -> None:
        self.calls: list[list[str]] = []

    def embed(self, texts):
        texts = list(texts)
        self.calls.append(texts)
        # A distinct but deterministic unit-ish vector per text; content is irrelevant here
        # because no test in this file asserts on ranking.
        return [[float((hash(t) % 97) + 1)] + [0.0] * (EMBEDDING_DIM - 1) for t in texts]


def write_pdf(path: Path, page_texts: list[str]) -> Path:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=(612, 792))
    for text in page_texts:
        c.drawString(72, 700, text)
        c.showPage()
    c.save()
    path.write_bytes(buf.getvalue())
    return path


@pytest.fixture
def corpus(tmp_path):
    """A two-file corpus directory, the shape `_converge_corpus` walks."""
    d = tmp_path / "corpus"
    d.mkdir()
    write_pdf(d / "alpha.pdf", ["alpha page one text", "alpha page two text"])
    write_pdf(d / "beta.pdf", ["beta page one text"])
    return d


def question(qid: str, expectation: str, sources: list[tuple[str, int]]) -> EvalQuestion:
    return EvalQuestion(
        id=qid,
        question="q?",
        class_slug="c",
        expectation=expectation,
        expected_sources=[ExpectedSource(file=f, page_or_slide=p) for f, p in sources],
        answer_notes="",
        suites=["smoke"],
        tags=[],
        added="2026-01-01",
    )


class TestConvergeCorpus:
    """ "Every corpus file ingested exactly once" - the property that makes re-running safe."""

    def test_ingests_every_file_once_on_a_cold_class(self, db, corpus):
        conn, owner_id, class_id = db
        embedder = FakeEmbeddings()

        ready = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus, embedder=embedder
        )

        assert sorted(ready) == ["alpha.pdf", "beta.pdf"]
        assert all(count > 0 for count in ready.values())
        assert embedder.calls, "a cold class must actually embed"

    def test_second_run_ingests_nothing_and_embeds_nothing(self, db, corpus):
        """THE anti-inflation property. `ingest_file` mints a fresh `file_id` every call and
        `index_file`'s idempotency is delete-by-file_id, so it can only ever replace a set WITHIN
        one file_id - never across runs. A runner that ingested unconditionally would add a
        complete duplicate chunk set on every run: the class doubles, retrieval fills its top-k
        with copies of one page, and every count printed goes with it.
        """
        conn, owner_id, class_id = db
        first = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )

        second_embedder = FakeEmbeddings()
        second = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=second_embedder,
        )

        assert second == first, "the census must not move on a re-run"
        assert second_embedder.calls == [], "a converged corpus must cost nothing to re-run"

    def test_empty_corpus_dir_is_a_setup_error(self, db, tmp_path):
        conn, owner_id, class_id = db
        empty = tmp_path / "empty"
        empty.mkdir()

        with pytest.raises(ask_smoke.SetupError, match="dogfood corpus is"):
            ask_smoke._converge_corpus(
                conn,
                owner_id=owner_id,
                class_id=class_id,
                corpus_dir=empty,
                embedder=FakeEmbeddings(),
            )

    def test_duplicate_ready_rows_warn_and_do_not_re_ingest(self, db, corpus, capsys):
        """The WARN branch, which the review found unexercised by everyone AND by the suite.

        It is the code added in response to a real incident (8 accumulated ingests of one deck),
        so leaving it unrun was exactly backwards. Duplicates must WARN, must NOT auto-delete
        (dropping chunk sets is not a bench's call), and must not re-ingest.
        """
        conn, owner_id, class_id = db
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )
        # Ingest alpha.pdf a SECOND time - the real-world failure, reproduced exactly: a fresh
        # file_id, so the delete-by-file_id idempotency never fires.
        ingest_file(corpus / "alpha.pdf", owner_id, class_id, embedder=FakeEmbeddings(), conn=conn)

        embedder = FakeEmbeddings()
        ready = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus, embedder=embedder
        )
        out = capsys.readouterr().out

        assert "WARN" in out and "alpha.pdf" in out
        assert "ingested more than once" in out
        assert "DUPLICATED" in out
        assert embedder.calls == [], "a duplicate must never trigger another ingest"
        # The reported count is the INFLATED total, and saying so is the point of the warning.
        assert ready["alpha.pdf"] == 2 * 2  # two pages, twice


class TestResolveClass:
    def test_creates_then_finds_the_same_class(self, db):
        conn, owner_id, _ = db

        created = ask_smoke._resolve_class(conn, owner_id, "some-slug")
        found = ask_smoke._resolve_class(conn, owner_id, "some-slug")

        assert created == found

    def test_duplicate_classes_are_refused_not_resolved(self, db):
        """Picking either row would split the corpus across two class_ids, and every count
        printed afterwards would be over half a class."""
        conn, owner_id, _ = db
        ask_smoke._resolve_class(conn, owner_id, "dupe")
        conn.execute(
            "insert into classes (class_id, owner_id, name) values (gen_random_uuid(), %s, %s)",
            (owner_id, "dupe"),
        )

        with pytest.raises(ask_smoke.SetupError, match="corpus is split"):
            ask_smoke._resolve_class(conn, owner_id, "dupe")


# The `(file, page)` pairs a corpus is pretending to have, for the guard's page census.
INDEXED = {("present.pdf", 1), ("present.pdf", 2), ("present.pdf", 3)}


class TestSetupValidityGuards:
    """The guards answer one question: is this run SCOREABLE at all?"""

    def test_missing_expected_file_is_refused(self):
        """A file the corpus lacks scores as a MISS on every question citing it - an
        honest-looking 0% recall that is really a missing file."""
        questions = [question("q001", "answer", [("absent.pdf", 1)])]

        with pytest.raises(ask_smoke.SetupError, match="not ingested"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_in_corpus_question_without_sources_is_refused(self):
        """The silent-denominator hole: `retrieval_hit([], ...)` returns None, `compute_metrics`
        drops None rows, and the file-existence loop iterates SOURCES - so a sourceless answer row
        left the recall denominator with no warning at all, inflating the hit rate."""
        questions = [question("q009", "answer", [])]

        with pytest.raises(ask_smoke.SetupError, match="no 'expected_sources'"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_expected_page_with_no_indexed_chunk_is_refused(self):
        """The page half of the pair, which the file-level check throws away.

        `retrieval_hit` compares `(file, page_or_slide)`, so a page carrying no chunk is exactly as
        unhittable as a missing file — and it is the half this corpus is ambiguous about, since
        `Livingston Cosmogony.pdf` index-page 4 is PRINTED "200". Unguarded, writing 200 there posts
        `hit=no` forever with the report blaming retrieval.
        """
        questions = [question("q007", "answer", [("present.pdf", 99)])]

        with pytest.raises(ask_smoke.SetupError, match="no indexed chunk"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_ready_file_whose_chunks_were_deleted_is_refused(self):
        """A `ready` files row with zero chunks reads as "already ingested" to `_converge_corpus`,
        so the filename IS in `ready` and the file-level check passes. It contributes no pages,
        which is what this catches. Reachable from the duplicate-ingest WARN's own two-step
        remediation ("delete the chunks rows, then those files rows") if you stop in between.
        """
        questions = [question("q001", "answer", [("emptied.pdf", 1)])]

        with pytest.raises(ask_smoke.SetupError, match="no indexed chunk"):
            ask_smoke._require_expected_files(questions, {"emptied.pdf": 0}, INDEXED)

    def test_indexed_pages_reads_back_the_pair_retrieval_compares(self, db, corpus):
        """`_indexed_pages` must return exactly the `(file, int page)` shape `retrieval_hit` uses.

        The column is `text`, so a missing conversion would make every census check a false alarm.
        """
        conn, owner_id, class_id = db
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )

        indexed = ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=class_id)

        assert ("alpha.pdf", 1) in indexed and ("alpha.pdf", 2) in indexed
        assert ("beta.pdf", 1) in indexed
        assert all(isinstance(page, int) for _, page in indexed)
        # And the real suite's shape: a page the corpus does not have is simply absent.
        assert ("alpha.pdf", 99) not in indexed

    def test_indexed_pages_is_scoped_to_this_owner_and_class(self, db, corpus, tmp_path):
        """The F6/F12 isolation filter, pinned — the assertion the other test CANNOT make.

        Found by mutation: deleting `where owner_id AND class_id` from `_indexed_pages` left the
        whole suite green, because nothing planted a `(file, page)` pair that ONLY the scope filter
        excludes. An unscoped read is not a cosmetic breach: another owner's page would satisfy the
        setup guard, the run would proceed, and retrieval — which IS scoped — could never return it,
        so the bench would post `hit=no` forever and blame retrieval. That is precisely the
        bad-ground-truth-reported-as-a-system-failure outcome the guard exists to prevent.

        The Retriever's own consistency guard carries the same rule for the same reason
        (`retriever.md`: "the guard is not exempt from the isolation filter").
        """
        conn, owner_id, class_id = db
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )

        # A SECOND owner/class carrying a filename+page that exists nowhere in the first.
        other_owner = f"other-owner-{uuid.uuid4()}"
        other_class = str(uuid.uuid4())
        other_dir = tmp_path / "other"
        other_dir.mkdir()
        write_pdf(other_dir / "someone-elses.pdf", ["a page belonging to another owner"])
        try:
            conn.execute(
                "insert into classes (class_id, owner_id, name) values (%s::uuid, %s, %s)",
                (other_class, other_owner, "other class"),
            )
            ingest_file(
                other_dir / "someone-elses.pdf",
                other_owner,
                other_class,
                embedder=FakeEmbeddings(),
                conn=conn,
            )

            indexed = ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=class_id)

            assert ("alpha.pdf", 1) in indexed, "own rows must still be there"
            assert ("someone-elses.pdf", 1) not in indexed, (
                "_indexed_pages leaked another owner's page — the owner_id/class_id filter is gone"
            )

            # Same class_id, different owner, and vice versa: BOTH halves of the predicate matter.
            assert ask_smoke._indexed_pages(conn, owner_id=other_owner, class_id=class_id) == set()
            assert ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=other_class) == set()
        finally:
            # The `db` fixture tears down ITS owner only, so this one cleans up after itself.
            conn.execute("delete from chunks where owner_id = %s", (other_owner,))
            conn.execute("delete from files where owner_id = %s", (other_owner,))
            conn.execute("delete from classes where owner_id = %s", (other_owner,))
            conn.commit()

    def test_refuse_rows_are_allowed_to_have_no_sources(self):
        """The same emptiness is CORRECT out-of-corpus - `expected_sources` is in-corpus only
        (ADR 0021 §3). The guard must not confuse the two."""
        questions = [
            question("q001", "answer", [("present.pdf", 1)]),
            question("q010", "refuse", []),
        ]

        ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)  # must not raise


class TestExitGate:
    """Issue #8's acceptance criterion, read minimally: >=1 GROUNDED, >=1 REFUSAL."""

    @staticmethod
    def _metrics(records):
        from gct.eval.scoring import compute_metrics

        return compute_metrics(records)

    def test_passes_with_one_of_each(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is True

    def test_fails_without_a_grounded_answer(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.REFUSAL, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_fails_without_an_honest_refusal(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.GROUNDED),  # hallucinated
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_gate_line_splits_grounded_from_partial(self, capsys):
        """A run of 1 GROUNDED + 7 PARTIAL printing a bare "8/8" above "PASS" is literally
        accurate and completely misleading - PARTIAL is the TRACKED bucket, explicitly not a pass
        (ADR 0023 §2/§5). The last line is what a human skims, so the split prints inline."""
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = (
            [EvalRecord("answer", GrounderState.GROUNDED, hit=True)]
            + [EvalRecord("answer", GrounderState.PARTIAL, hit=True) for _ in range(7)]
            + [EvalRecord("refuse", GrounderState.REFUSAL)]
        )

        ask_smoke._print_gate(records, self._metrics(records))
        out = capsys.readouterr().out

        assert "8/8" in out
        assert "1 GROUNDED + 7 PARTIAL" in out


def grounder_result(state, prose, gaps):
    """A `GrounderResult` with only the fields `_print_verbose` reads populated."""
    from gct.grounder.answer import Coverage, GrounderResult, Integrity

    return GrounderResult(
        state=state,
        answer_prose=prose,
        citations=[],
        coverage=Coverage(complete=not gaps, gaps=list(gaps)),
        integrity=Integrity(ok=True, reasons=[]),
        error=None,
    )


class TestOnlyFilter:
    """`--only` (issue #60): re-ask a hand-picked subset cheaply, without lying about it."""

    QUESTIONS = [
        question("q001", "answer", [("present.pdf", 1)]),
        question("q005", "answer", [("present.pdf", 2)]),
        question("q009", "refuse", []),
    ]

    def test_no_flag_is_the_whole_suite_untouched(self):
        assert ask_smoke._select(self.QUESTIONS, None) is self.QUESTIONS

    def test_selects_exactly_the_named_ids(self):
        selected = ask_smoke._select(self.QUESTIONS, "q005")

        assert [q.id for q in selected] == ["q005"]

    def test_comma_separated_ids_select_all_of_them_in_suite_order(self):
        """Suite order, not command-line order: the per-question lines are meant to be diffed
        against the same lines from a full run."""
        selected = ask_smoke._select(self.QUESTIONS, "q009,q001")

        assert [q.id for q in selected] == ["q001", "q009"]

    def test_whitespace_around_ids_is_tolerated(self):
        assert [q.id for q in ask_smoke._select(self.QUESTIONS, " q005 , q009 ")] == [
            "q005",
            "q009",
        ]

    def test_unknown_id_is_a_setup_error_naming_it(self):
        """A typo must never quietly run a smaller suite than intended - and this one is the
        cheapest of all to miss, since `--only q05` matching nothing would ask ZERO questions and
        then print a tidy report of them."""
        with pytest.raises(ask_smoke.SetupError, match="does not contain") as exc:
            ask_smoke._select(self.QUESTIONS, "q05")

        assert "'q05'" in str(exc.value)

    def test_a_partly_unknown_id_list_is_refused_whole(self):
        """One good id does not license running the run: the caller asked for two questions."""
        with pytest.raises(ask_smoke.SetupError, match="'q999'"):
            ask_smoke._select(self.QUESTIONS, "q005,q999")

    def test_the_filter_is_applied_after_the_suite_filter(self):
        """`--suite smoke --only q005` means "q005, IF smoke has it". An id in the eval file but
        not in this suite is therefore unknown HERE, and must be refused rather than resurrected."""
        smoke_only = [q for q in self.QUESTIONS if q.id != "q009"]

        with pytest.raises(ask_smoke.SetupError, match="'q009'"):
            ask_smoke._select(smoke_only, "q009")

    def test_empty_id_list_is_a_setup_error(self):
        with pytest.raises(ask_smoke.SetupError, match="names no question ids"):
            ask_smoke._select(self.QUESTIONS, " , ")

    def test_notice_names_the_ids_and_refuses_to_report_rates(self, capsys):
        """What prints INSTEAD of the rate vector. Rates over a hand-picked subset are the
        "clean rate over a suite that quietly shrank" this whole script exists to prevent - the
        difference being that here the shrinking was asked for, so it is named rather than
        refused. The gate is suppressed for its own reason: >=1 GROUNDED AND >=1 REFUSAL is
        structurally unreachable for a one-question run, so running it would print FAIL for a run
        that answered exactly what it was asked."""
        ask_smoke._print_filtered_notice(ask_smoke._select(self.QUESTIONS, "q005"), 12, [])
        out = capsys.readouterr().out

        assert "FILTERED RUN" in out
        assert "1 of 12" in out
        assert "q005" in out
        assert "No ADR 0023 rate vector" in out
        assert "not comparable" in out
        assert "No exit gate" in out
        # The rate vector's own labels must be nowhere near this output.
        assert "grounded_pass_rate" not in out
        assert "PASS" not in out and "FAIL" not in out
        # And with no ERROR rows there is no error line to print (see the next two tests).
        assert "ERROR" not in out

    def test_notice_reports_errors_as_a_count_never_a_rate(self, capsys):
        """The one aggregate that survives the suppression, and it is a COUNT, never a rate.
        The per-question lines above it already name each ERROR (state, outcome=EXCLUDED, kind
        and message), so this line is a summary convenience: it keeps a multi-question probe
        from ending on a quiet closing block while an earlier ask errored. Conditional on
        purpose — see `_print_filtered_notice`'s docstring for the bargain, which differs from
        the bench health line's always-printed one."""
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        selected = ask_smoke._select(self.QUESTIONS, "q001,q005")
        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("answer", GrounderState.ERROR, hit=None),
        ]

        ask_smoke._print_filtered_notice(selected, 12, records)
        out = capsys.readouterr().out

        assert "1 of 2 question(s) came back ERROR" in out
        assert "error_rate" not in out  # a count, never a rate — rates stay suppressed

    def test_default_args_leave_both_new_flags_off(self, monkeypatch):
        """The byte-identical-default guarantee, at the parse layer: absent flags mean a default
        run takes neither new branch."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        args = ask_smoke._parse_args()

        assert args.only is None
        assert args.verbose is False

    def test_flags_parse(self, monkeypatch):
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--only", "q005,q009", "--verbose"])

        args = ask_smoke._parse_args()

        assert args.only == "q005,q009"
        assert args.verbose is True


class TestVerbose:
    """`--verbose` (issue #60): the probe has to be able to see its own subject."""

    def test_prints_full_prose_and_untruncated_gaps(self, capsys):
        """`_detail` never prints the prose at all, and clips gaps at 80 chars - but the gap
        WORDING is the evidence a generation probe compares across repeated asks."""
        from gct.grounder.answer import GrounderState

        long_gap = "the sources do not cover " + "x" * 200
        # A blank paragraph break in the prose, because that is what a real answer carries.
        result = grounder_result(GrounderState.PARTIAL, "line one\n\nline two", [long_gap, "and b"])

        ask_smoke._print_verbose(result)
        out = capsys.readouterr().out

        assert "answer_prose:" in out
        assert "| line one" in out and "| line two" in out
        assert not any(line.rstrip() != line for line in out.splitlines()), (
            "verbose output is diffed run-against-run; trailing whitespace is noise in that diff"
        )
        assert long_gap in out, "the gap list must NOT be clipped under --verbose"
        assert "..." not in out
        assert "gaps (2, un-truncated):" in out

    def test_none_prose_prints_no_block_and_never_the_word_none(self, capsys):
        """REFUSAL and ERROR carry no prose, by contract (`GrounderResult`). An empty block, or a
        literal "None", would read as something the model wrote."""
        from gct.grounder.answer import GrounderState

        result = grounder_result(GrounderState.REFUSAL, None, ["nothing on quantum chromodynamics"])

        ask_smoke._print_verbose(result)
        out = capsys.readouterr().out

        assert "answer_prose" not in out
        assert "None" not in out
        assert "nothing on quantum chromodynamics" in out

    def test_a_result_with_neither_prose_nor_gaps_prints_nothing(self, capsys):
        """An ERROR carries no prose and no gaps (`_error`), so verbose has nothing to add - and
        must add nothing rather than an empty labelled block."""
        from gct.grounder.answer import GrounderState

        ask_smoke._print_verbose(grounder_result(GrounderState.ERROR, None, []))

        assert capsys.readouterr().out == ""


class TestMainWiring:
    """The two new flags driven through `main()` itself — offline, no DB, no provider, no spend.

    The unit tests above prove `_select`, `_print_verbose` and `_print_filtered_notice` each work
    in isolation; none of them can notice `main()` failing to CALL one. (Mutation-checked in PR
    #63's review: deleting the `--verbose` call, or the whole `--only` early return, left every
    unit test green.) So these monkeypatch out exactly the seams that cost money or need
    Postgres, run the real `main()`, and assert on ONE captured buffer — where ordering is a
    checkable fact rather than something the test constructs itself.
    """

    QUESTIONS = [
        question("q001", "answer", [("present.pdf", 1)]),
        question("q005", "answer", [("present.pdf", 2)]),
        question("q009", "refuse", []),
    ]

    class _FakeConn:
        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    def _drive(self, monkeypatch, tmp_path, argv_tail, states=None):
        """Run `main()` with fakes at the seams. Question text is set to the question's id so
        the fake `ask` can answer per-question the way the real one would."""
        from gct.grounder.answer import GrounderState

        states = states or {
            "q001": (GrounderState.GROUNDED, "prose one [S1]", []),
            "q005": (GrounderState.GROUNDED, "prose five [S1]", []),
            "q009": (GrounderState.REFUSAL, None, ["nothing on this"]),
        }
        questions = [dataclasses.replace(q, question=q.id) for q in self.QUESTIONS]

        def fake_ask(conn, question_text, owner, class_id, *, embedder, generator, k):
            state, prose, gaps = states[question_text]
            return ask_smoke.AskResult(
                result=grounder_result(state, prose, gaps), retrieved=[], retrieval_ran=True
            )

        monkeypatch.setattr(ask_smoke, "_load", lambda path, suite: list(questions))
        monkeypatch.setattr(ask_smoke, "OpenAIEmbeddings", FakeEmbeddings)
        monkeypatch.setattr(ask_smoke, "OpenAIGeneration", object)
        monkeypatch.setattr(ask_smoke, "connect", self._FakeConn)
        monkeypatch.setattr(ask_smoke, "_resolve_class", lambda conn, owner, slug: uuid.uuid4())
        monkeypatch.setattr(ask_smoke, "_converge_corpus", lambda *a, **k: set())
        monkeypatch.setattr(ask_smoke, "_require_expected_files", lambda *a, **k: None)
        monkeypatch.setattr(ask_smoke, "_indexed_pages", lambda *a, **k: {})
        monkeypatch.setattr(ask_smoke, "_print_census", lambda *a, **k: None)
        monkeypatch.setattr(ask_smoke, "ask", fake_ask)
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--corpus-dir", str(tmp_path), *argv_tail])
        return ask_smoke.main()

    def test_a_default_run_reaches_the_bench_and_the_gate(self, monkeypatch, tmp_path, capsys):
        rc = self._drive(monkeypatch, tmp_path, [])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "grounded_pass_rate" in out
        assert "exit gate" in out
        assert "FILTERED RUN" not in out
        assert "answer_prose" not in out  # --verbose off is the default, through the real loop

    def test_only_takes_the_early_return_instead_of_the_bench(self, monkeypatch, tmp_path, capsys):
        rc = self._drive(monkeypatch, tmp_path, ["--only", "q005"])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "FILTERED RUN — 1 of 3" in out
        assert "grounded_pass_rate" not in out
        # The notice SAYS "No exit gate either", so match the gate's own verdict line, not the
        # phrase: neither verdict may print on a filtered run.
        assert "PASS — exit gate" not in out and "FAIL — exit gate" not in out

    def test_verbose_is_wired_and_prints_after_the_summary_line(
        self, monkeypatch, tmp_path, capsys
    ):
        """Order asserted in ONE buffer: the prose block sits between its own summary line and
        the notice. A two-capture `startswith` comparison builds the expected order itself and
        cannot see a reordering; an index chain over the real run's output can."""
        rc = self._drive(monkeypatch, tmp_path, ["--only", "q005", "--verbose"])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert out.index("q005 ") < out.index("answer_prose:") < out.index("FILTERED RUN")
        assert "prose five" in out

    def test_a_filtered_run_with_an_error_says_so_out_loud(self, monkeypatch, tmp_path, capsys):
        from gct.grounder.answer import GrounderState

        rc = self._drive(
            monkeypatch,
            tmp_path,
            ["--only", "q005"],
            states={"q005": (GrounderState.ERROR, None, [])},
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "1 of 1 question(s) came back ERROR" in out


class TestArgValidation:
    def test_k_below_one_exits_two_before_any_work(self, monkeypatch):
        """`--k 0` must die at parse time. Unvalidated it reached `retrieve()` mid-loop - AFTER
        the corpus was paid for - and exited 1, the code documented as "the gate failed"."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--k", "0"])

        with pytest.raises(SystemExit) as exc:
            ask_smoke._parse_args()

        assert exc.value.code == ask_smoke.EXIT_SETUP

    def test_default_k_is_the_retrievers_own(self, monkeypatch):
        from gct.retriever.retrieve import DEFAULT_K

        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        assert ask_smoke._parse_args().k == DEFAULT_K
