"""Tests for `scripts/ask_smoke.py` - the Slice 1 exit runner (issue #8, PR #44 review).

WHY A SCRIPT HAS TESTS AT ALL. ADR 0009 calls the scripts thin peer callers, and thin callers
usually earn none. This one is hundreds of lines and carries real branching that nothing else
covers:
corpus convergence, the duplicate-ingest WARN, the duplicate-class refusal, the setup-validity
guards, and the exit gate. Every defect found in PR #44's review lived in this file, and none of
them was visible from reading it - each needed the script RUN. The objection that running it costs
money is answered here: three independent reviewers each built a stub-provider harness to review
it, so the offline path plainly exists. This file is that harness, kept.

Everything here is OFFLINE and free - the real local Postgres (`db`), a fake embedder, and real
PDFs generated by reportlab. No `live` mark, no API key, nothing paid. Most tests stop before the
question loop; `TestMainWiring` runs the loop itself with `ask`, `connect` and both provider
classes monkeypatched to fakes, so no real provider is ever constructed and nothing can reach a
network call.

Every test taking `db` is automatically `db`-marked (tests/conftest.py derives it from the
fixture). A SKIP here locally means Postgres is down - it is not a pass.
"""

from __future__ import annotations

import dataclasses
import importlib.util
import io
import uuid
from pathlib import Path

import psycopg
import pytest
from reportlab.pdfgen import canvas

from gct.config import EMBEDDING_DIM, Settings
from gct.eval.questions import EvalQuestion, ExpectedSource
from gct.ingest.chunk import CHUNK_OVERLAP_WORDS, CHUNK_SIZE_WORDS
from gct.ingest.pipeline import ingest_file
from gct.retriever.retrieve import RetrievedChunk

# Import the script by PATH rather than by package name: `scripts/` is deliberately not a package
# (ADR 0009 - the scripts are peers of the library, not part of it), so there is nothing to
# `import`. Loading the file directly keeps that boundary intact instead of bending sys.path.
_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "ask_smoke.py"
_spec = importlib.util.spec_from_file_location("ask_smoke_under_test", _SCRIPT)
ask_smoke = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ask_smoke)

# `_converge_corpus` takes the chunk window as REQUIRED keyword args (it threads them to
# `ingest_file`, and its caller prints them), so every call here has to supply one. All but one
# test (`test_the_chunk_window_reaches_ingest`, which varies the window deliberately) assert chunk
# counts at the module defaults, so they share this dict rather than restating a literal per call.
WINDOW = {"chunk_size": CHUNK_SIZE_WORDS, "chunk_overlap": CHUNK_OVERLAP_WORDS}


class FakeEmbeddings:
    """Deterministic, free, and LOUD if a test embeds when it should not have.

    `calls` is the assertion surface for convergence: the whole point of checking before ingesting
    is that a second run costs nothing, and the only way to prove "nothing" is that the embedder
    was never touched.
    """

    model_id = "fake-embed-3"

    def __init__(self) -> None:
        self.calls: list[list[str]] = []

    def embed(self, texts):
        texts = list(texts)
        self.calls.append(texts)
        # A distinct but deterministic unit-ish vector per text; content is irrelevant here
        # because no test in this file asserts on ranking.
        return [[float((hash(t) % 97) + 1)] + [0.0] * (EMBEDDING_DIM - 1) for t in texts]


def write_pdf(path: Path, page_texts: list[str]) -> Path:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=(612, 792))
    for text in page_texts:
        c.drawString(72, 700, text)
        c.showPage()
    c.save()
    path.write_bytes(buf.getvalue())
    return path


@pytest.fixture
def corpus(tmp_path):
    """A two-file corpus directory, the shape `_converge_corpus` walks."""
    d = tmp_path / "corpus"
    d.mkdir()
    write_pdf(d / "alpha.pdf", ["alpha page one text", "alpha page two text"])
    write_pdf(d / "beta.pdf", ["beta page one text"])
    return d


def question(qid: str, expectation: str, sources: list[tuple[str, int]]) -> EvalQuestion:
    return EvalQuestion(
        id=qid,
        question="q?",
        class_slug="c",
        expectation=expectation,
        expected_sources=[ExpectedSource(file=f, page_or_slide=p) for f, p in sources],
        answer_notes="",
        suites=["smoke"],
        tags=[],
        added="2026-01-01",
    )


class TestConvergeCorpus:
    """ "Every corpus file ingested exactly once" - the property that makes re-running safe."""

    def test_ingests_every_file_once_on_a_cold_class(self, db, corpus):
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        embedder = FakeEmbeddings()

        ready, ingested = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=embedder,
            **WINDOW,
        )

        assert sorted(ready) == ["alpha.pdf", "beta.pdf"]
        assert all(count > 0 for count in ready.values())
        assert ingested == 2, "a cold class ingests every file THIS run"
        assert embedder.calls, "a cold class must actually embed"

    def test_second_run_ingests_nothing_and_embeds_nothing(self, db, corpus):
        """THE anti-inflation property. `ingest_file` mints a fresh `file_id` every call and
        `index_file`'s idempotency is delete-by-file_id, so it can only ever replace a set WITHIN
        one file_id - never across runs. A runner that ingested unconditionally would add a
        complete duplicate chunk set on every run: the class doubles, retrieval fills its top-k
        with copies of one page, and every count printed goes with it.
        """
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        first, _ = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            **WINDOW,
        )

        second_embedder = FakeEmbeddings()
        second, second_ingested = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=second_embedder,
            **WINDOW,
        )

        assert second == first, "the census must not move on a re-run"
        assert second_ingested == 0, "a converged corpus reports zero files ingested this run"
        assert second_embedder.calls == [], "a converged corpus must cost nothing to re-run"

    def test_the_chunk_window_reaches_ingest(self, db, corpus):
        """The THREADING claim, which no arg-parsing test can make: a window handed to this
        function must reach `chunk_units`, or `--chunk-size` would print in the header and the
        census and change nothing about the chunks being scored.

        Every generated page is four words, so a 2-word window with 1-word overlap (stride 1)
        cuts each page into THREE chunks - a count that neither the default 250/40 window (one
        chunk per page) nor a zero-overlap fallback (two per page) can produce, so BOTH halves
        of the window must have arrived intact for this to pass.
        """
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)

        ready, _ = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            chunk_size=2,
            chunk_overlap=1,
        )

        assert ready == {"alpha.pdf": 6, "beta.pdf": 3}

    def test_empty_corpus_dir_is_a_setup_error(self, db, tmp_path):
        conn, owner_id, class_id = db
        empty = tmp_path / "empty"
        empty.mkdir()

        with pytest.raises(ask_smoke.SetupError, match="dogfood corpus is"):
            ask_smoke._converge_corpus(
                conn,
                owner_id=owner_id,
                class_id=class_id,
                corpus_dir=empty,
                embedder=FakeEmbeddings(),
                **WINDOW,
            )

    def test_duplicate_ready_rows_warn_and_do_not_re_ingest(self, db, corpus, capsys):
        """The WARN branch, which the review found unexercised by everyone AND by the suite.

        It is the code added in response to a real incident (8 accumulated ingests of one deck),
        so leaving it unrun was exactly backwards. Duplicates must WARN, must NOT auto-delete
        (dropping chunk sets is not a bench's call), and must not re-ingest.
        """
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            **WINDOW,
        )
        # Ingest alpha.pdf a SECOND time - the real-world failure, reproduced exactly: a fresh
        # file_id, so the delete-by-file_id idempotency never fires.
        ingest_file(corpus / "alpha.pdf", owner_id, class_id, embedder=FakeEmbeddings(), conn=conn)

        embedder = FakeEmbeddings()
        ready, _ = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=embedder,
            **WINDOW,
        )
        out = capsys.readouterr().out

        assert "WARN" in out and "alpha.pdf" in out
        assert "ingested more than once" in out
        assert "DUPLICATED" in out
        assert embedder.calls == [], "a duplicate must never trigger another ingest"
        # The reported count is the INFLATED total, and saying so is the point of the warning.
        assert ready["alpha.pdf"] == 2 * 2  # two pages, twice

    def test_partial_convergence_counts_only_files_ingested_this_run(self, db, corpus):
        """`ingested` is the THIS-RUN count, not the ready count. The cold-class and re-run tests
        pin it only at its two extremes (everything / nothing), so an implementation wrong only in
        between - say, one that reports `len(ready)` whenever anything was ingested - would pass
        both. One file pre-ingested + one missing is the smallest case that sits between them."""
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        ingest_file(corpus / "alpha.pdf", owner_id, class_id, embedder=FakeEmbeddings(), conn=conn)

        ready, ingested = ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            **WINDOW,
        )

        assert sorted(ready) == ["alpha.pdf", "beta.pdf"]
        assert ingested == 1


class TestPrintCensus:
    """The census must not label stored chunks with the requested window: the window is a fact
    about the COMMAND LINE, and only files ingested THIS run are known to carry it. Three wordings,
    keyed on `ingested` vs `len(ready)` - each pinned here because `TestMainWiring` stubs this
    function out, so nothing else ever executes it.
    """

    def _census_out(self, db, ingested, capsys):
        conn, owner_id, class_id = db
        ask_smoke._print_census(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            ready={"alpha.pdf": 4, "beta.pdf": 2},
            chunk_size=150,
            chunk_overlap=25,
            ingested=ingested,
        )
        return capsys.readouterr().out

    def test_everything_ingested_labels_the_window_as_applied(self, db, capsys):
        out = self._census_out(db, ingested=2, capsys=capsys)
        assert "all ingested this run at chunk window 150/25 words" in out

    def test_nothing_ingested_says_the_requested_window_did_not_apply(self, db, capsys):
        """The reuse trap itself: an owner that already had a corpus. The old line asserted the
        requested window as stored fact; this pins the honest wording that replaced it."""
        out = self._census_out(db, ingested=0, capsys=capsys)
        assert "none ingested this run" in out
        assert "requested window 150/25 words did not apply" in out
        assert "keep the window that made them" in out

    def test_mixed_ingestion_names_both_counts(self, db, capsys):
        out = self._census_out(db, ingested=1, capsys=capsys)
        assert "1 of 2 file(s) ingested this run at the requested window 150/25 words" in out
        assert "the rest keep the window that made them" in out


class TestResolveClass:
    def test_creates_then_finds_the_same_class(self, db):
        conn, owner_id, _ = db

        created = ask_smoke._resolve_class(conn, owner_id, "some-slug")
        found = ask_smoke._resolve_class(conn, owner_id, "some-slug")

        assert created == found

    def test_duplicate_classes_are_refused_not_resolved(self, db):
        """Picking either row would split the corpus across two class_ids, and every count
        printed afterwards would be over half a class."""
        conn, owner_id, _ = db
        ask_smoke._resolve_class(conn, owner_id, "dupe")
        conn.execute(
            "insert into classes (class_id, owner_id, name) values (gen_random_uuid(), %s, %s)",
            (owner_id, "dupe"),
        )

        with pytest.raises(ask_smoke.SetupError, match="corpus is split"):
            ask_smoke._resolve_class(conn, owner_id, "dupe")


# The `(file, page)` pairs a corpus is pretending to have, for the guard's page census.
INDEXED = {("present.pdf", 1), ("present.pdf", 2), ("present.pdf", 3)}


class TestSetupValidityGuards:
    """The guards answer one question: is this run SCOREABLE at all?"""

    def test_missing_expected_file_is_refused(self):
        """A file the corpus lacks scores as a MISS on every question citing it - an
        honest-looking 0% recall that is really a missing file."""
        questions = [question("q001", "answer", [("absent.pdf", 1)])]

        with pytest.raises(ask_smoke.SetupError, match="not ingested"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_in_corpus_question_without_sources_is_refused(self):
        """The silent-denominator hole: `retrieval_hit([], ...)` returns None, `compute_metrics`
        drops None rows, and the file-existence loop iterates SOURCES - so a sourceless answer row
        left the recall denominator with no warning at all, inflating the hit rate."""
        questions = [question("q009", "answer", [])]

        with pytest.raises(ask_smoke.SetupError, match="no 'expected_sources'"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_expected_page_with_no_indexed_chunk_is_refused(self):
        """The page half of the pair, which the file-level check throws away.

        `retrieval_hit` compares `(file, page_or_slide)`, so a page carrying no chunk is exactly as
        unhittable as a missing file — and it is the half this corpus is ambiguous about, since
        `Livingston Cosmogony.pdf` index-page 4 is PRINTED "200". Unguarded, writing 200 there posts
        `hit=no` forever with the report blaming retrieval.
        """
        questions = [question("q007", "answer", [("present.pdf", 99)])]

        with pytest.raises(ask_smoke.SetupError, match="no indexed chunk"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)

    def test_ready_file_whose_chunks_were_deleted_is_refused(self):
        """A `ready` files row with zero chunks reads as "already ingested" to `_converge_corpus`,
        so the filename IS in `ready` and the file-level check passes. It contributes no pages,
        which is what this catches. Reachable from the duplicate-ingest WARN's own two-step
        remediation ("delete the chunks rows, then those files rows") if you stop in between.
        """
        questions = [question("q001", "answer", [("emptied.pdf", 1)])]

        with pytest.raises(ask_smoke.SetupError, match="no indexed chunk"):
            ask_smoke._require_expected_files(questions, {"emptied.pdf": 0}, INDEXED)

    def test_indexed_pages_reads_back_the_pair_retrieval_compares(self, db, corpus):
        """`_indexed_pages` must return exactly the `(file, int page)` shape `retrieval_hit` uses.

        The column is `text`, so a missing conversion would make every census check a false alarm.
        """
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            **WINDOW,
        )

        indexed = ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=class_id)

        assert ("alpha.pdf", 1) in indexed and ("alpha.pdf", 2) in indexed
        assert ("beta.pdf", 1) in indexed
        assert all(isinstance(page, int) for _, page in indexed)
        # And the real suite's shape: a page the corpus does not have is simply absent.
        assert ("alpha.pdf", 99) not in indexed

    def test_indexed_pages_is_scoped_to_this_owner_and_class(self, db, corpus, tmp_path):
        """The F6/F12 isolation filter, pinned — the assertion the other test CANNOT make.

        Found by mutation: deleting `where owner_id AND class_id` from `_indexed_pages` left the
        whole suite green, because nothing planted a `(file, page)` pair that ONLY the scope filter
        excludes. An unscoped read is not a cosmetic breach: another owner's page would satisfy the
        setup guard, the run would proceed, and retrieval — which IS scoped — could never return it,
        so the bench would post `hit=no` forever and blame retrieval. That is precisely the
        bad-ground-truth-reported-as-a-system-failure outcome the guard exists to prevent.

        The Retriever's own consistency guard carries the same rule for the same reason
        (`retriever.md`: "the guard is not exempt from the isolation filter").
        """
        conn, owner_id, class_id = db
        conn.autocommit = True  # the script's wiring (ADR 0025, guarded per ADR 0027)
        ask_smoke._converge_corpus(
            conn,
            owner_id=owner_id,
            class_id=class_id,
            corpus_dir=corpus,
            embedder=FakeEmbeddings(),
            **WINDOW,
        )

        # A SECOND owner/class carrying a filename+page that exists nowhere in the first.
        other_owner = f"other-owner-{uuid.uuid4()}"
        other_class = str(uuid.uuid4())
        other_dir = tmp_path / "other"
        other_dir.mkdir()
        write_pdf(other_dir / "someone-elses.pdf", ["a page belonging to another owner"])
        try:
            conn.execute(
                "insert into classes (class_id, owner_id, name) values (%s::uuid, %s, %s)",
                (other_class, other_owner, "other class"),
            )
            ingest_file(
                other_dir / "someone-elses.pdf",
                other_owner,
                other_class,
                embedder=FakeEmbeddings(),
                conn=conn,
            )

            indexed = ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=class_id)

            assert ("alpha.pdf", 1) in indexed, "own rows must still be there"
            assert ("someone-elses.pdf", 1) not in indexed, (
                "_indexed_pages leaked another owner's page — the owner_id/class_id filter is gone"
            )

            # Same class_id, different owner, and vice versa: BOTH halves of the predicate matter.
            assert ask_smoke._indexed_pages(conn, owner_id=other_owner, class_id=class_id) == set()
            assert ask_smoke._indexed_pages(conn, owner_id=owner_id, class_id=other_class) == set()
        finally:
            # The `db` fixture tears down ITS owner only, so this one cleans up after itself.
            conn.execute("delete from chunks where owner_id = %s", (other_owner,))
            conn.execute("delete from files where owner_id = %s", (other_owner,))
            conn.execute("delete from classes where owner_id = %s", (other_owner,))
            conn.commit()

    def test_refuse_rows_are_allowed_to_have_no_sources(self):
        """The same emptiness is CORRECT out-of-corpus - `expected_sources` is in-corpus only
        (ADR 0021 §3). The guard must not confuse the two."""
        questions = [
            question("q001", "answer", [("present.pdf", 1)]),
            question("q010", "refuse", []),
        ]

        ask_smoke._require_expected_files(questions, {"present.pdf": 3}, INDEXED)  # must not raise


class TestExitGate:
    """Issue #8's acceptance criterion, read minimally: >=1 GROUNDED, >=1 REFUSAL."""

    @staticmethod
    def _metrics(records):
        from gct.eval.scoring import compute_metrics

        return compute_metrics(records)

    def test_passes_with_one_of_each(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is True

    def test_fails_without_a_grounded_answer(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.REFUSAL, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_fails_without_an_honest_refusal(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.GROUNDED),  # hallucinated
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_gate_line_splits_grounded_from_partial(self, capsys):
        """A run of 1 GROUNDED + 7 PARTIAL printing a bare "8/8" above "PASS" is literally
        accurate and completely misleading - PARTIAL is the TRACKED bucket, explicitly not a pass
        (ADR 0023 §2/§5). The last line is what a human skims, so the split prints inline."""
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = (
            [EvalRecord("answer", GrounderState.GROUNDED, hit=True)]
            + [EvalRecord("answer", GrounderState.PARTIAL, hit=True) for _ in range(7)]
            + [EvalRecord("refuse", GrounderState.REFUSAL)]
        )

        ask_smoke._print_gate(records, self._metrics(records))
        out = capsys.readouterr().out

        assert "8/8" in out
        assert "1 GROUNDED + 7 PARTIAL" in out


def grounder_result(state, prose, gaps):
    """A `GrounderResult` with only the fields `_print_verbose` reads populated."""
    from gct.grounder.answer import Coverage, GrounderResult, Integrity

    return GrounderResult(
        state=state,
        answer_prose=prose,
        citations=[],
        coverage=Coverage(complete=not gaps, gaps=list(gaps)),
        integrity=Integrity(ok=True, reasons=[]),
        error=None,
    )


def retrieved_chunks(rows) -> list[RetrievedChunk]:
    """`[(file, page, score), ...]` -> the top-k list, IN THE ORDER GIVEN.

    Order is never re-sorted here, deliberately: `AskResult.retrieved` is "the EXACT top-k list
    handed to the Grounder, in rank order", and a helper that tidied it would hide exactly the
    out-of-order case `expected_placement` is specified against.
    """
    return [
        RetrievedChunk(chunk_id=f"chunk-{i}", text="…", file=file, page_or_slide=page, score=score)
        for i, (file, page, score) in enumerate(rows, start=1)
    ]


def ask_result(state, prose, gaps, retrieved, retrieval_ran=True):
    """A canned `AskResult` — the whole reason these tests cost nothing.

    `_print_retrieved` takes `(EvalQuestion, AskResult)` and reads nothing else, so the retrieval
    report can be driven end to end with no provider, no database and no spend.
    """
    return ask_smoke.AskResult(
        result=grounder_result(state, prose, gaps),
        retrieved=retrieved_chunks(retrieved),
        retrieval_ran=retrieval_ran,
    )


class TestOnlyFilter:
    """`--only` (issue #60): re-ask a hand-picked subset cheaply, without lying about it."""

    QUESTIONS = [
        question("q001", "answer", [("present.pdf", 1)]),
        question("q005", "answer", [("present.pdf", 2)]),
        question("q009", "refuse", []),
    ]

    def test_no_flag_is_the_whole_suite_untouched(self):
        assert ask_smoke._select(self.QUESTIONS, None) is self.QUESTIONS

    def test_selects_exactly_the_named_ids(self):
        selected = ask_smoke._select(self.QUESTIONS, "q005")

        assert [q.id for q in selected] == ["q005"]

    def test_comma_separated_ids_select_all_of_them_in_suite_order(self):
        """Suite order, not command-line order: the per-question lines are meant to be diffed
        against the same lines from a full run."""
        selected = ask_smoke._select(self.QUESTIONS, "q009,q001")

        assert [q.id for q in selected] == ["q001", "q009"]

    def test_whitespace_around_ids_is_tolerated(self):
        assert [q.id for q in ask_smoke._select(self.QUESTIONS, " q005 , q009 ")] == [
            "q005",
            "q009",
        ]

    def test_unknown_id_is_a_setup_error_naming_it(self):
        """A typo must never quietly run a smaller suite than intended - and this one is the
        cheapest of all to miss, since `--only q05` matching nothing would ask ZERO questions and
        then print a tidy report of them."""
        with pytest.raises(ask_smoke.SetupError, match="does not contain") as exc:
            ask_smoke._select(self.QUESTIONS, "q05")

        assert "'q05'" in str(exc.value)

    def test_a_partly_unknown_id_list_is_refused_whole(self):
        """One good id does not license running the run: the caller asked for two questions."""
        with pytest.raises(ask_smoke.SetupError, match="'q999'"):
            ask_smoke._select(self.QUESTIONS, "q005,q999")

    def test_the_filter_is_applied_after_the_suite_filter(self):
        """`--suite smoke --only q005` means "q005, IF smoke has it". An id in the eval file but
        not in this suite is therefore unknown HERE, and must be refused rather than resurrected."""
        smoke_only = [q for q in self.QUESTIONS if q.id != "q009"]

        with pytest.raises(ask_smoke.SetupError, match="'q009'"):
            ask_smoke._select(smoke_only, "q009")

    def test_empty_id_list_is_a_setup_error(self):
        with pytest.raises(ask_smoke.SetupError, match="names no question ids"):
            ask_smoke._select(self.QUESTIONS, " , ")

    def test_notice_names_the_ids_and_refuses_to_report_rates(self, capsys):
        """What prints INSTEAD of the rate vector. Rates over a hand-picked subset are the
        "clean rate over a suite that quietly shrank" this whole script exists to prevent - the
        difference being that here the shrinking was asked for, so it is named rather than
        refused. The gate is suppressed for its own reason: >=1 GROUNDED AND >=1 REFUSAL is
        structurally unreachable for a one-question run, so running it would print FAIL for a run
        that answered exactly what it was asked."""
        ask_smoke._print_filtered_notice(ask_smoke._select(self.QUESTIONS, "q005"), 12, [])
        out = capsys.readouterr().out

        assert "FILTERED RUN" in out
        assert "1 of 12" in out
        assert "q005" in out
        assert "No ADR 0023 rate vector" in out
        assert "not comparable" in out
        assert "No exit gate" in out
        # The rate vector's own labels must be nowhere near this output.
        assert "grounded_pass_rate" not in out
        assert "PASS" not in out and "FAIL" not in out
        # And with no ERROR rows there is no error line to print (see the next two tests).
        assert "ERROR" not in out

    def test_notice_reports_errors_as_a_count_never_a_rate(self, capsys):
        """The one aggregate that survives the suppression, and it is a COUNT, never a rate.
        The per-question lines above it already name each ERROR (state, outcome=EXCLUDED, kind
        and message), so this line is a summary convenience: it keeps a multi-question probe
        from ending on a quiet closing block while an earlier ask errored. Conditional on
        purpose — see `_print_filtered_notice`'s docstring for the bargain, which differs from
        the bench health line's always-printed one."""
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        selected = ask_smoke._select(self.QUESTIONS, "q001,q005")
        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("answer", GrounderState.ERROR, hit=None),
        ]

        ask_smoke._print_filtered_notice(selected, 12, records)
        out = capsys.readouterr().out

        assert "1 of 2 question(s) came back ERROR" in out
        assert "error_rate" not in out  # a count, never a rate — rates stay suppressed

    def test_default_args_leave_both_new_flags_off(self, monkeypatch):
        """The byte-identical-default guarantee, at the parse layer: absent flags mean a default
        run takes neither new branch."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        args = ask_smoke._parse_args()

        assert args.only is None
        assert args.verbose is False

    def test_flags_parse(self, monkeypatch):
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--only", "q005,q009", "--verbose"])

        args = ask_smoke._parse_args()

        assert args.only == "q005,q009"
        assert args.verbose is True


class TestVerbose:
    """`--verbose` (issue #60): the probe has to be able to see its own subject."""

    def test_prints_full_prose_and_untruncated_gaps(self, capsys):
        """`_detail` never prints the prose at all, and clips gaps at 80 chars - but the gap
        WORDING is the evidence a generation probe compares across repeated asks."""
        from gct.grounder.answer import GrounderState

        long_gap = "the sources do not cover " + "x" * 200
        # A blank paragraph break in the prose, because that is what a real answer carries.
        result = grounder_result(GrounderState.PARTIAL, "line one\n\nline two", [long_gap, "and b"])

        ask_smoke._print_verbose(result)
        out = capsys.readouterr().out

        assert "answer_prose:" in out
        assert "| line one" in out and "| line two" in out
        assert not any(line.rstrip() != line for line in out.splitlines()), (
            "verbose output is diffed run-against-run; trailing whitespace is noise in that diff"
        )
        assert long_gap in out, "the gap list must NOT be clipped under --verbose"
        assert "..." not in out
        assert "gaps (2, un-truncated):" in out

    def test_none_prose_prints_no_block_and_never_the_word_none(self, capsys):
        """REFUSAL and ERROR carry no prose, by contract (`GrounderResult`). An empty block, or a
        literal "None", would read as something the model wrote."""
        from gct.grounder.answer import GrounderState

        result = grounder_result(GrounderState.REFUSAL, None, ["nothing on quantum chromodynamics"])

        ask_smoke._print_verbose(result)
        out = capsys.readouterr().out

        assert "answer_prose" not in out
        assert "None" not in out
        assert "nothing on quantum chromodynamics" in out

    def test_a_result_with_neither_prose_nor_gaps_prints_nothing(self, capsys):
        """An ERROR carries no prose and no gaps (`_error`), so verbose has nothing to add - and
        must add nothing rather than an empty labelled block."""
        from gct.grounder.answer import GrounderState

        ask_smoke._print_verbose(grounder_result(GrounderState.ERROR, None, []))

        assert capsys.readouterr().out == ""


class TestMainWiring:
    """The two new flags driven through `main()` itself — offline, no DB, no provider, no spend.

    The unit tests above prove `_select`, `_print_verbose` and `_print_filtered_notice` each work
    in isolation; none of them can notice `main()` failing to CALL one. (Mutation-checked in PR
    #63's review: deleting the `--verbose` call, or the whole `--only` early return, left every
    unit test green.) So these monkeypatch out exactly the seams that cost money or need
    Postgres, run the real `main()`, and assert on ONE captured buffer — where ordering is a
    checkable fact rather than something the test constructs itself.
    """

    QUESTIONS = [
        question("q001", "answer", [("present.pdf", 1)]),
        question("q005", "answer", [("present.pdf", 2)]),
        question("q009", "refuse", []),
    ]

    class _FakeConn:
        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    def _drive(self, monkeypatch, tmp_path, argv_tail, states=None, retrieved=None):
        """Run `main()` with fakes at the seams. Question text is set to the question's id so
        the fake `ask` can answer per-question the way the real one would.

        `retrieved` maps a question id to `[(file, page, score), ...]` and DEFAULTS TO AN EMPTY
        top-k for every question - which is what keeps every test written before
        `--show-retrieved` existed unaffected by this parameter.
        """
        from gct.grounder.answer import GrounderState

        states = states or {
            "q001": (GrounderState.GROUNDED, "prose one [S1]", []),
            "q005": (GrounderState.GROUNDED, "prose five [S1]", []),
            "q009": (GrounderState.REFUSAL, None, ["nothing on this"]),
        }
        rows = retrieved or {}
        questions = [dataclasses.replace(q, question=q.id) for q in self.QUESTIONS]

        def fake_ask(conn, question_text, owner, class_id, *, embedder, generator, k):
            state, prose, gaps = states[question_text]
            return ask_result(state, prose, gaps, rows.get(question_text, []))

        monkeypatch.setattr(ask_smoke, "_load", lambda path, suite: list(questions))
        # The wiring block reads the key through `load_settings` before constructing providers.
        # Stubbed like every other seam here - NOT for isolation only, but because this must not
        # depend on the ambient environment: in CI OPENAI_API_KEY is genuinely empty, so an
        # unstubbed read would trip the empty-key SetupError inside every test that drives main().
        monkeypatch.setattr(
            ask_smoke,
            "load_settings",
            lambda: Settings(database_url="postgresql://localhost:5432/x", openai_api_key="sk-t"),
        )
        monkeypatch.setattr(ask_smoke, "OpenAIEmbeddings", FakeEmbeddings)
        monkeypatch.setattr(ask_smoke, "OpenAIGeneration", object)
        monkeypatch.setattr(ask_smoke, "connect", self._FakeConn)
        monkeypatch.setattr(ask_smoke, "_resolve_class", lambda conn, owner, slug: uuid.uuid4())
        monkeypatch.setattr(ask_smoke, "_converge_corpus", lambda *a, **k: ({}, 0))
        monkeypatch.setattr(ask_smoke, "_require_expected_files", lambda *a, **k: None)
        monkeypatch.setattr(ask_smoke, "_indexed_pages", lambda *a, **k: {})
        monkeypatch.setattr(ask_smoke, "_print_census", lambda *a, **k: None)
        monkeypatch.setattr(ask_smoke, "ask", fake_ask)
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--corpus-dir", str(tmp_path), *argv_tail])
        return ask_smoke.main()

    def test_a_default_run_reaches_the_bench_and_the_gate(self, monkeypatch, tmp_path, capsys):
        rc = self._drive(monkeypatch, tmp_path, [])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "grounded_pass_rate" in out
        assert "exit gate" in out
        assert "FILTERED RUN" not in out
        assert "answer_prose" not in out  # --verbose off is the default, through the real loop

    def test_only_takes_the_early_return_instead_of_the_bench(self, monkeypatch, tmp_path, capsys):
        rc = self._drive(monkeypatch, tmp_path, ["--only", "q005"])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "FILTERED RUN — 1 of 3" in out
        assert "grounded_pass_rate" not in out
        # The notice SAYS "No exit gate either", so match the gate's own verdict line, not the
        # phrase: neither verdict may print on a filtered run.
        assert "PASS — exit gate" not in out and "FAIL — exit gate" not in out

    def test_verbose_is_wired_and_prints_after_the_summary_line(
        self, monkeypatch, tmp_path, capsys
    ):
        """Order asserted in ONE buffer: the prose block sits between its own summary line and
        the notice. A two-capture `startswith` comparison builds the expected order itself and
        cannot see a reordering; an index chain over the real run's output can."""
        rc = self._drive(monkeypatch, tmp_path, ["--only", "q005", "--verbose"])
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert out.index("q005 ") < out.index("answer_prose:") < out.index("FILTERED RUN")
        assert "prose five" in out

    def test_a_filtered_run_with_an_error_says_so_out_loud(self, monkeypatch, tmp_path, capsys):
        from gct.grounder.answer import GrounderState

        rc = self._drive(
            monkeypatch,
            tmp_path,
            ["--only", "q005"],
            states={"q005": (GrounderState.ERROR, None, [])},
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "1 of 1 question(s) came back ERROR" in out


class TestArgValidation:
    def test_k_below_one_exits_two_before_any_work(self, monkeypatch):
        """`--k 0` must die at parse time. Unvalidated it reached `retrieve()` mid-loop - AFTER
        the corpus was paid for - and exited 1, the code documented as "the gate failed"."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--k", "0"])

        with pytest.raises(SystemExit) as exc:
            ask_smoke._parse_args()

        assert exc.value.code == ask_smoke.EXIT_SETUP

    def test_default_k_is_the_retrievers_own(self, monkeypatch):
        from gct.retriever.retrieve import DEFAULT_K

        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        assert ask_smoke._parse_args().k == DEFAULT_K

    @pytest.mark.parametrize(
        ("size", "overlap"),
        [("100", "100"), ("100", "150"), ("100", "-1"), ("0", "0")],
        ids=["overlap-equals-size", "overlap-exceeds-size", "negative-overlap", "zero-size"],
    )
    def test_invalid_chunk_window_exits_two_before_any_work(self, monkeypatch, size, overlap):
        """`--k 0`'s failure shape, one stage earlier. Unvalidated, an invalid window reaches
        `chunk_units` and raises mid-ingest - after every file before it in the corpus was parsed,
        embedded and paid for - exiting 1, the code documented as "the gate failed"."""
        monkeypatch.setattr(
            "sys.argv", ["ask_smoke.py", "--chunk-size", size, "--chunk-overlap", overlap]
        )

        with pytest.raises(SystemExit) as exc:
            ask_smoke._parse_args()

        assert exc.value.code == ask_smoke.EXIT_SETUP

    @pytest.mark.parametrize(("size", "overlap"), [(400, 60), (150, 0)])
    def test_a_valid_chunk_window_is_accepted(self, monkeypatch, size, overlap):
        """The other side of the check, including `overlap=0` - legal, and the boundary a
        `0 < overlap` typo in the guard would reject."""
        monkeypatch.setattr(
            "sys.argv",
            ["ask_smoke.py", "--chunk-size", str(size), "--chunk-overlap", str(overlap)],
        )

        args = ask_smoke._parse_args()

        assert (args.chunk_size, args.chunk_overlap) == (size, overlap)

    def test_default_chunk_window_is_the_chunkers_own(self, monkeypatch):
        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        args = ask_smoke._parse_args()

        assert (args.chunk_size, args.chunk_overlap) == (CHUNK_SIZE_WORDS, CHUNK_OVERLAP_WORDS)


class TestWiringSetupFailures:
    """Provider and DB wiring failures are SETUP failures (exit 2), never gate failures (exit 1).

    The distinction is `SetupError`'s own: "it ran and lost" vs "it never ran". Before the wiring
    boundary converted them, all three paths below raised straight through `except SetupError` and
    exited 1 with a traceback - a typo'd `.env` indistinguishable from a system that answered
    badly. Each test drives the REAL `main()` up to the wiring block and fails it there; nothing
    is stubbed past the failure point, so the exit code is the one a user would see.
    """

    QUESTIONS = [question("q001", "answer", [("present.pdf", 1)])]

    def _drive(self, monkeypatch, tmp_path, *, key="sk-test", **overrides):
        questions = list(self.QUESTIONS)
        monkeypatch.setattr(ask_smoke, "_load", lambda path, suite: questions)
        monkeypatch.setattr(
            ask_smoke,
            "load_settings",
            lambda: Settings(database_url="postgresql://localhost:5432/x", openai_api_key=key),
        )
        for name, value in overrides.items():
            monkeypatch.setattr(ask_smoke, name, value)
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--corpus-dir", str(tmp_path)])
        return ask_smoke.main()

    def test_empty_api_key_exits_two_before_any_client_exists(self, monkeypatch, tmp_path, capsys):
        """The real missing-key path: `load_settings()` defaults an unset OPENAI_API_KEY to "",
        which the OpenAI client ACCEPTS at construction - so without the explicit check the
        failure lands at the first paid call, mid-ingest, as exit 1."""

        def boom(*a, **k):
            raise AssertionError("no client may be constructed on an empty key")

        rc = self._drive(
            monkeypatch, tmp_path, key="", OpenAIEmbeddings=boom, OpenAIGeneration=boom
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_SETUP
        assert "SETUP FAILED" in out
        assert "OPENAI_API_KEY is empty" in out

    def test_provider_construction_error_exits_two(self, monkeypatch, tmp_path, capsys):
        from openai import OpenAIError

        def boom(*a, **k):
            raise OpenAIError("no api_key client option")

        rc = self._drive(monkeypatch, tmp_path, OpenAIEmbeddings=boom)
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_SETUP
        assert "SETUP FAILED" in out
        assert "cannot construct the OpenAI providers" in out

    def test_unreachable_database_exits_two(self, monkeypatch, tmp_path, capsys):
        def refuse():
            raise psycopg.OperationalError("connection refused")

        rc = self._drive(
            monkeypatch,
            tmp_path,
            OpenAIEmbeddings=FakeEmbeddings,
            OpenAIGeneration=object,
            connect=refuse,
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_SETUP
        assert "SETUP FAILED" in out
        assert "cannot connect to Postgres" in out


# Issue #67's own measurement (2026-08-01): q005's real top-5, with the expected slide THIRD
# behind two copies of a different author's critique. `0.5648 - 0.5432 = 0.0216` is the margin the
# bench could not previously say, and every reference assertion below is anchored to it.
LECTURE = "Lecture 20 Evolutionist-Creationist Debate.pptx"
LIVINGSTON = "Livingston Cosmogony.pdf"
Q005_ROWS = [
    (LIVINGSTON, 13, 0.6189),
    (LIVINGSTON, 13, 0.5820),
    (LECTURE, 2, 0.5648),
    (LIVINGSTON, 13, 0.5432),
    (LIVINGSTON, 13, 0.5364),
]


class TestShowRetrieved:
    """`--show-retrieved` (issue #67): the retrieval probe, offline and free.

    `retrieval_hit` is an ANY-MATCH rule (ADR 0023 §1), so `hit=yes` says the expected chunk is
    SOMEWHERE in the top-k and nothing about what outranks it. Every test here drives the printer
    on a CANNED `AskResult` - no provider, no database, no spend - which is possible precisely
    because `_print_retrieved` takes `(EvalQuestion, AskResult)` and reads nothing else.

    What these defend, over and above "it prints something": the three `None`-shaped cases are
    three DIFFERENT facts (no expectation / looked-and-missed / found-at-the-last-row) and none of
    them may render as a zero, because a fabricated `0.0000` in a diagnostic is worse than no
    diagnostic.
    """

    EXPECTED = [(LECTURE, 2)]

    def _print(self, capsys, rows, sources=None, retrieval_ran=True, state=None):
        """Render one question's retrieval block and return it.

        `sources=None` means the default in-corpus question (expects `LECTURE` p.2); passing `[]`
        builds the OUT-OF-CORPUS row, which carries no `expected_sources` at all - the tri-state's
        third case, and the one a caller must not confuse with a miss.
        """
        from gct.grounder.answer import GrounderState

        if sources is None:
            sources = self.EXPECTED
        expectation = "answer" if sources else "refuse"
        q = question("q005" if sources else "q009", expectation, sources)
        result = ask_result(
            state or GrounderState.GROUNDED, "prose [S1]", [], rows, retrieval_ran=retrieval_ran
        )

        ask_smoke._print_retrieved(q, result)
        return capsys.readouterr().out

    def test_default_args_leave_show_retrieved_off(self, monkeypatch):
        """The byte-identical-default guarantee at the parse layer: an absent flag means a
        default run never takes the new branch."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        assert ask_smoke._parse_args().show_retrieved is False

    @pytest.mark.parametrize(
        "argv_tail",
        [
            ["--show-retrieved"],
            ["--show-retrieved", "--only", "q005"],
            ["--show-retrieved", "--verbose"],
            ["--only", "q005", "--show-retrieved", "--verbose"],
        ],
        ids=["alone", "with-only", "with-verbose", "with-both"],
    )
    def test_the_flag_parses(self, monkeypatch, argv_tail):
        """Its own flag, composable with the others. `--verbose` is the GENERATION probe and this
        is the RETRIEVAL probe; ADR 0023 §1 keeps those two signals unconflated at the metric
        layer, so fusing them into one flag would re-conflate them at the reporting layer."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", *argv_tail])

        args = ask_smoke._parse_args()

        assert args.show_retrieved is True
        assert args.verbose is ("--verbose" in argv_tail)

    def test_the_q005_block_renders_the_reference_table(self, capsys):
        """THE ACCEPTANCE TEST — issue #67's own table, and the sentence `hit=yes` could not say.

        All four provenance fields per row, in the handed order, the marker on the expected row
        ONLY, and the rank/margin line. `0.5648 - 0.5432 = 0.0216`: a margin defined the other way
        round (deficit behind the leader) would print `0.0541` here.
        """
        out = self._print(capsys, Q005_ROWS)

        assert "retrieved top-5" in out
        assert "rank   score  source" in out
        for _file, page, score in Q005_ROWS:
            assert f"{score:.4f}" in out
            assert f"p.{page}" in out
        # Order as handed, never re-sorted — `AskResult.retrieved` is the exact list the Grounder
        # was given, so a re-sort here would report a rank the Grounder never saw.
        assert out.index("0.6189") < out.index("0.5648") < out.index("0.5364")
        assert out.count("<-- expected") == 1
        assert "0.5648  Lecture 20 Evolutionist-Creationist Debate.pptx p.2   <-- expected" in out
        assert "expected source: rank 3 of 5, margin over rank 4 = +0.0216" in out

    def test_every_matching_row_is_marked_when_the_source_appears_twice(self, capsys):
        """A single marker on a source that appears twice would say the top-k contained it once —
        one summary figure hiding composition, which is this issue's own complaint."""
        rows = [
            (LIVINGSTON, 13, 0.6189),
            (LECTURE, 2, 0.5820),
            (LIVINGSTON, 13, 0.5648),
            (LECTURE, 2, 0.5432),
            (LIVINGSTON, 13, 0.5364),
        ]

        out = self._print(capsys, rows)

        assert out.count("<-- expected") == 2
        assert "rank 2 of 5 (also at rank 4)" in out
        assert "margin over rank 3 = +0.0172" in out  # measured from the BEST rank, not the last

    def test_an_absent_expected_source_prints_no_margin_number(self, capsys):
        """THE NO-FABRICATION PIN. A measured miss has no rank, so it has nothing to have a
        margin FROM — and a `0.0000` there would be a figure nobody measured."""
        rows = [(LIVINGSTON, 13, 0.6189 - i / 100) for i in range(5)]

        out = self._print(capsys, rows)

        assert "ABSENT" in out
        assert "hit=no" in out
        assert "margin over" not in out
        assert "0.0000" not in out

    def test_the_last_row_case_says_n_a_and_never_prints_a_zero_margin(self, capsys):
        """`None` means UNDEFINED — nothing ranks below the last row. `+0.0000` would read as
        "tied with the next row", a measurement that was never made (the argument `_pct` carries
        about rates, one layer down). Exact mirror of the tie test below."""
        rows = [
            (LIVINGSTON, 13, 0.6189),
            (LIVINGSTON, 13, 0.5820),
            (LECTURE, 2, 0.5648),
        ]

        out = self._print(capsys, rows)

        assert "rank 3 of 3" in out
        assert "margin n/a (last row" in out
        assert "0.0000" not in out

    def test_a_tie_prints_a_measured_zero_margin(self, capsys):
        """The other half of the pair: `0.0` is a MEASUREMENT, and it prints as one. The note
        says what it means — `retrieve()` orders by distance with no tiebreak, so which of two
        tied rows came first is arbitrary and may swap between runs."""
        rows = [
            (LIVINGSTON, 13, 0.6189),
            (LECTURE, 2, 0.5820),
            (LIVINGSTON, 13, 0.5820),
            (LIVINGSTON, 13, 0.5364),
        ]

        out = self._print(capsys, rows)

        assert "margin over rank 3 = +0.0000" in out
        assert "arbitrary" in out
        assert "margin n/a" not in out

    def test_an_out_of_corpus_row_prints_the_table_but_says_n_a_not_absent(self, capsys):
        """n/a is NOT a miss. A refuse row carries no `expected_sources` (ADR 0021 §3), so there
        was nothing to look for — and calling that ABSENT would report a miss the suite never
        scored. The table still prints: an out-of-corpus row's composition is exactly FINDINGS'
        "attractor slides" observation, and it is free."""
        out = self._print(capsys, Q005_ROWS, sources=[])

        assert "retrieved top-5" in out  # the table is NOT suppressed
        assert "expected source: n/a" in out
        assert "ADR 0021" in out
        assert "ABSENT" not in out
        assert "<-- expected" not in out
        assert "margin" not in out

    def test_retrieval_never_ran_prints_no_table_at_all(self, capsys):
        """The two retrieval-side ERROR paths produced NO top-k, so there is none to print.
        Fabricating one — even an empty one — would report a measurement that never happened,
        mirroring how the summary line already suppresses `hit` to `n/a` on those rows."""
        from gct.grounder.answer import GrounderState

        out = self._print(capsys, [], retrieval_ran=False, state=GrounderState.ERROR)

        assert "retrieval never ran" in out
        assert "retrieval-side ERROR" in out
        assert "retrieved top-" not in out
        assert "rank   score  source" not in out

    def test_an_empty_result_set_prints_the_empty_class_wording_and_no_rows(self, capsys):
        """Retrieval RAN and returned nothing: an empty/un-ingested class (retriever.md). That is
        a measured miss, said in those words — never "nothing matched", which would blame
        retrieval for a corpus that was never there."""
        out = self._print(capsys, [])

        assert "retrieved 0 chunks" in out
        assert "empty/un-ingested class" in out
        assert "rank   score  source" not in out
        assert "0.0000" not in out

    def test_no_line_carries_trailing_whitespace(self, capsys):
        """This output is diffed run-against-run; invisible whitespace is noise in that diff.
        The same assertion the `--verbose` prose test makes."""
        out = self._print(capsys, Q005_ROWS)

        assert not any(line.rstrip() != line for line in out.splitlines())

    def test_a_long_filename_is_printed_in_full(self, capsys):
        """NEVER `_clip`. The file+page pair IS the payload — it is what `retrieval_hit` compares
        and what a citation names — so a truncated `Lecture 20 Evolutionist-Crea...` would defeat
        the block's only purpose. A wide line is the accepted cost (issue #67 §Risks)."""
        long_name = "Lecture " + "x" * 108 + ".pptx"
        assert len(long_name) == 121

        out = self._print(capsys, [(long_name, 2, 0.5)], sources=[(long_name, 2)])

        assert long_name in out
        assert "..." not in out

    def test_scores_print_at_four_decimals(self, capsys):
        """Four decimals, matching `eval/FINDINGS.md`, so a row pasted out of a run is directly
        comparable with the measurements recorded there."""
        out = self._print(capsys, [(LECTURE, 2, 0.5), (LIVINGSTON, 13, 0.25)])

        assert "0.5000" in out
        assert "0.2500" in out


class TestShowRetrievedWiring:
    """`--show-retrieved` driven through the REAL `main()` — the seam no unit test can see.

    PR #63's review found this hole empirically: deleting `main()`'s `--verbose` call left every
    unit test above green. A printer that works perfectly and is never called prints nothing, so
    the flag needs at least one test that runs the loop.

    Reuses `TestMainWiring`'s recipe verbatim (its `_drive`, its fakes, its questions) rather than
    subclassing it, so those tests are not silently re-run under a second name.
    """

    QUESTIONS = TestMainWiring.QUESTIONS
    _FakeConn = TestMainWiring._FakeConn
    _drive = TestMainWiring._drive

    # q001 expects `present.pdf` p.1 and q005 expects p.2 (see `TestMainWiring.QUESTIONS`), so
    # these rows put each question's expected source at a KNOWN rank with a known margin.
    ROWS = {
        "q001": [("present.pdf", 1, 0.90), ("other.pdf", 9, 0.80)],
        "q005": [
            ("other.pdf", 9, 0.6189),
            ("other.pdf", 9, 0.5820),
            ("present.pdf", 2, 0.5648),
            ("other.pdf", 9, 0.5432),
            ("other.pdf", 9, 0.5364),
        ],
        "q009": [("other.pdf", 9, 0.70)],
    }

    def test_main_wires_the_flag_and_prints_one_block_per_question(
        self, monkeypatch, tmp_path, capsys
    ):
        """THE MUTATION-CHECKED SEAM: deleting `if args.show_retrieved:` from `main()` fails
        HERE and nowhere else."""
        rc = self._drive(monkeypatch, tmp_path, ["--show-retrieved"], retrieved=self.ROWS)
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert out.count("retrieved top-") == 3, "one block per question, including the refuse row"
        assert "expected source: rank 3 of 5, margin over rank 4 = +0.0216" in out
        assert "expected source: n/a" in out  # the refuse row, not a miss

    def test_a_default_run_prints_no_retrieved_block(self, monkeypatch, tmp_path, capsys):
        """The byte-identical-default guarantee, through the real loop rather than the parser."""
        rc = self._drive(monkeypatch, tmp_path, [], retrieved=self.ROWS)
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "retrieved top-" not in out
        assert "expected source" not in out

    def test_show_retrieved_prints_between_the_summary_line_and_the_prose(
        self, monkeypatch, tmp_path, capsys
    ):
        """ORDER, asserted as an index chain over ONE real buffer — a two-capture comparison
        would build the expected order itself and could not see a reordering.

        Retrieval happened BEFORE generation, so a reader following "why did it answer that"
        reads the evidence, then the answer.
        """
        rc = self._drive(
            monkeypatch,
            tmp_path,
            ["--only", "q005", "--show-retrieved", "--verbose"],
            retrieved=self.ROWS,
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert (
            out.index("q005 ")
            < out.index("retrieved top-5")
            < out.index("expected source:")
            < out.index("answer_prose:")
            < out.index("FILTERED RUN")
        )

    def test_show_retrieved_alone_prints_no_prose(self, monkeypatch, tmp_path, capsys):
        """The unconflation, testable: you can look at retrieval composition WITHOUT a wall of
        model prose. That is why this is its own flag and not a second meaning for `--verbose`."""
        rc = self._drive(
            monkeypatch, tmp_path, ["--only", "q005", "--show-retrieved"], retrieved=self.ROWS
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "retrieved top-5" in out
        assert "answer_prose" not in out

    def test_verbose_alone_prints_no_retrieved_block(self, monkeypatch, tmp_path, capsys):
        """The other direction — `--verbose`'s emitted bytes are unchanged by this PR."""
        rc = self._drive(
            monkeypatch, tmp_path, ["--only", "q005", "--verbose"], retrieved=self.ROWS
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "answer_prose" in out
        assert "retrieved top-" not in out

    def test_the_per_question_summary_line_is_identical_with_and_without_the_flag(
        self, monkeypatch, tmp_path, capsys
    ):
        """STRICTLY ADDITIVE means the line above the block does not move by one byte — that is
        what keeps a probe run diffable against the bench run it is probing."""
        self._drive(monkeypatch, tmp_path, [], retrieved=self.ROWS)
        plain = capsys.readouterr().out
        self._drive(monkeypatch, tmp_path, ["--show-retrieved"], retrieved=self.ROWS)
        flagged = capsys.readouterr().out

        def summary_lines(text):
            return [
                line
                for line in text.splitlines()
                if line.startswith(("  q001", "  q005", "  q009"))
            ]

        assert summary_lines(plain) == summary_lines(flagged)
        assert len(summary_lines(plain)) == 3

    @pytest.mark.parametrize("gate", ["passing", "failing"], ids=["gate-passes", "gate-fails"])
    def test_the_exit_code_and_gate_verdict_are_identical_with_and_without_the_flag(
        self, monkeypatch, tmp_path, capsys, gate
    ):
        """ISSUE #67'S "NO CHANGE TO ANY STATE" CLAIM, MADE MECHANICAL — on BOTH gate outcomes,
        since a flag that only preserved the passing verdict would still be a behavior change."""
        from gct.grounder.answer import GrounderState

        states = None
        if gate == "failing":
            # No in-corpus GROUNDED -> the gate fails and main() returns EXIT_GATE_FAILED.
            states = {
                "q001": (GrounderState.REFUSAL, None, ["nope"]),
                "q005": (GrounderState.REFUSAL, None, ["nope"]),
                "q009": (GrounderState.REFUSAL, None, ["nothing on this"]),
            }

        plain_rc = self._drive(monkeypatch, tmp_path, [], states=states, retrieved=self.ROWS)
        plain = capsys.readouterr().out
        flag_rc = self._drive(
            monkeypatch, tmp_path, ["--show-retrieved"], states=states, retrieved=self.ROWS
        )
        flagged = capsys.readouterr().out

        expected_rc = ask_smoke.EXIT_OK if gate == "passing" else ask_smoke.EXIT_GATE_FAILED
        assert plain_rc == flag_rc == expected_rc

        def verdict(text):
            return [line for line in text.splitlines() if "exit gate" in line]

        assert verdict(plain) == verdict(flagged)
        assert len(verdict(plain)) == 1

    def test_show_retrieved_with_only_still_takes_the_filtered_early_return(
        self, monkeypatch, tmp_path, capsys
    ):
        """The flag must not resurrect the rate vector on a subset run. Rates over a hand-picked
        subset are not comparable to a full run, and that suppression is independent of what the
        per-question lines print."""
        rc = self._drive(
            monkeypatch, tmp_path, ["--only", "q005", "--show-retrieved"], retrieved=self.ROWS
        )
        out = capsys.readouterr().out

        assert rc == ask_smoke.EXIT_OK
        assert "FILTERED RUN — 1 of 3" in out
        assert "retrieved top-5" in out
        assert "grounded_pass_rate" not in out
        assert "PASS — exit gate" not in out and "FAIL — exit gate" not in out

    def test_the_rate_vector_is_byte_identical_with_and_without_the_flag(
        self, monkeypatch, tmp_path, capsys
    ):
        """THE STRONGEST SINGLE STATEMENT OF "REPORTING ONLY": from `Summary — ADR 0023` to the
        end of the run, the two outputs are character-for-character the same string.

        `expected_placement` is called only from the printer and never from the record-building
        path, so no rate, no count and no verdict can move."""
        self._drive(monkeypatch, tmp_path, [], retrieved=self.ROWS)
        plain = capsys.readouterr().out
        self._drive(monkeypatch, tmp_path, ["--show-retrieved"], retrieved=self.ROWS)
        flagged = capsys.readouterr().out

        marker = "Summary — ADR 0023"
        assert marker in plain and marker in flagged
        assert plain[plain.index(marker) :] == flagged[flagged.index(marker) :]
