"""Tests for `scripts/ask_smoke.py` - the Slice 1 exit runner (issue #8, PR #44 review).

WHY A SCRIPT HAS TESTS AT ALL. ADR 0009 calls the scripts thin peer callers, and thin callers
usually earn none. This one is 495 lines and carries real branching that nothing else covers:
corpus convergence, the duplicate-ingest WARN, the duplicate-class refusal, the setup-validity
guards, and the exit gate. Every defect found in PR #44's review lived in this file, and none of
them was visible from reading it - each needed the script RUN. The objection that running it costs
money is answered here: three independent reviewers each built a stub-provider harness to review
it, so the offline path plainly exists. This file is that harness, kept.

Everything here is OFFLINE and free - the real local Postgres (`db`), a fake embedder, and real
PDFs generated by reportlab. No `live` mark, no API key, nothing paid. The generator is never
constructed at all: every test stops before the question loop, which is the part that would spend.

Every test taking `db` is automatically `db`-marked (tests/conftest.py derives it from the
fixture). A SKIP here locally means Postgres is down - it is not a pass.
"""
from __future__ import annotations

import importlib.util
import io
from pathlib import Path

import pytest
from reportlab.pdfgen import canvas

from gct.config import EMBEDDING_DIM
from gct.eval.questions import EvalQuestion, ExpectedSource

# Import the script by PATH rather than by package name: `scripts/` is deliberately not a package
# (ADR 0009 - the scripts are peers of the library, not part of it), so there is nothing to
# `import`. Loading the file directly keeps that boundary intact instead of bending sys.path.
_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "ask_smoke.py"
_spec = importlib.util.spec_from_file_location("ask_smoke_under_test", _SCRIPT)
ask_smoke = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ask_smoke)


class FakeEmbeddings:
    """Deterministic, free, and LOUD if a test embeds when it should not have.

    `calls` is the assertion surface for convergence: the whole point of checking before ingesting
    is that a second run costs nothing, and the only way to prove "nothing" is that the embedder
    was never touched.
    """

    model_id = "fake-embed-3"

    def __init__(self) -> None:
        self.calls: list[list[str]] = []

    def embed(self, texts):
        texts = list(texts)
        self.calls.append(texts)
        # A distinct but deterministic unit-ish vector per text; content is irrelevant here
        # because no test in this file asserts on ranking.
        return [[float((hash(t) % 97) + 1)] + [0.0] * (EMBEDDING_DIM - 1) for t in texts]


def write_pdf(path: Path, page_texts: list[str]) -> Path:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=(612, 792))
    for text in page_texts:
        c.drawString(72, 700, text)
        c.showPage()
    c.save()
    path.write_bytes(buf.getvalue())
    return path


@pytest.fixture
def corpus(tmp_path):
    """A two-file corpus directory, the shape `_converge_corpus` walks."""
    d = tmp_path / "corpus"
    d.mkdir()
    write_pdf(d / "alpha.pdf", ["alpha page one text", "alpha page two text"])
    write_pdf(d / "beta.pdf", ["beta page one text"])
    return d


def question(qid: str, expectation: str, sources: list[tuple[str, int]]) -> EvalQuestion:
    return EvalQuestion(
        id=qid,
        question="q?",
        class_slug="c",
        expectation=expectation,
        expected_sources=[ExpectedSource(file=f, page_or_slide=p) for f, p in sources],
        answer_notes="",
        suites=["smoke"],
        tags=[],
        added="2026-01-01",
    )


class TestConvergeCorpus:
    """"Every corpus file ingested exactly once" - the property that makes re-running safe."""

    def test_ingests_every_file_once_on_a_cold_class(self, db, corpus):
        conn, owner_id, class_id = db
        embedder = FakeEmbeddings()

        ready = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus, embedder=embedder
        )

        assert sorted(ready) == ["alpha.pdf", "beta.pdf"]
        assert all(count > 0 for count in ready.values())
        assert embedder.calls, "a cold class must actually embed"

    def test_second_run_ingests_nothing_and_embeds_nothing(self, db, corpus):
        """THE anti-inflation property. `ingest_file` mints a fresh `file_id` every call and
        `index_file`'s idempotency is delete-by-file_id, so it can only ever replace a set WITHIN
        one file_id - never across runs. A runner that ingested unconditionally would add a
        complete duplicate chunk set on every run: the class doubles, retrieval fills its top-k
        with copies of one page, and every count printed goes with it.
        """
        conn, owner_id, class_id = db
        first = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )

        second_embedder = FakeEmbeddings()
        second = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus,
            embedder=second_embedder,
        )

        assert second == first, "the census must not move on a re-run"
        assert second_embedder.calls == [], "a converged corpus must cost nothing to re-run"

    def test_empty_corpus_dir_is_a_setup_error(self, db, tmp_path):
        conn, owner_id, class_id = db
        empty = tmp_path / "empty"
        empty.mkdir()

        with pytest.raises(ask_smoke.SetupError, match="dogfood corpus is"):
            ask_smoke._converge_corpus(
                conn, owner_id=owner_id, class_id=class_id, corpus_dir=empty,
                embedder=FakeEmbeddings(),
            )

    def test_duplicate_ready_rows_warn_and_do_not_re_ingest(self, db, corpus, capsys):
        """The WARN branch, which the review found unexercised by everyone AND by the suite.

        It is the code added in response to a real incident (8 accumulated ingests of one deck),
        so leaving it unrun was exactly backwards. Duplicates must WARN, must NOT auto-delete
        (dropping chunk sets is not a bench's call), and must not re-ingest.
        """
        conn, owner_id, class_id = db
        ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus,
            embedder=FakeEmbeddings(),
        )
        # Ingest alpha.pdf a SECOND time - the real-world failure, reproduced exactly: a fresh
        # file_id, so the delete-by-file_id idempotency never fires.
        from gct.ingest.pipeline import ingest_file

        ingest_file(corpus / "alpha.pdf", owner_id, class_id,
                    embedder=FakeEmbeddings(), conn=conn)

        embedder = FakeEmbeddings()
        ready = ask_smoke._converge_corpus(
            conn, owner_id=owner_id, class_id=class_id, corpus_dir=corpus, embedder=embedder
        )
        out = capsys.readouterr().out

        assert "WARN" in out and "alpha.pdf" in out
        assert "ingested more than once" in out
        assert "DUPLICATED" in out
        assert embedder.calls == [], "a duplicate must never trigger another ingest"
        # The reported count is the INFLATED total, and saying so is the point of the warning.
        assert ready["alpha.pdf"] == 2 * 2  # two pages, twice


class TestResolveClass:
    def test_creates_then_finds_the_same_class(self, db):
        conn, owner_id, _ = db

        created = ask_smoke._resolve_class(conn, owner_id, "some-slug")
        found = ask_smoke._resolve_class(conn, owner_id, "some-slug")

        assert created == found

    def test_duplicate_classes_are_refused_not_resolved(self, db):
        """Picking either row would split the corpus across two class_ids, and every count
        printed afterwards would be over half a class."""
        conn, owner_id, _ = db
        ask_smoke._resolve_class(conn, owner_id, "dupe")
        conn.execute(
            "insert into classes (class_id, owner_id, name) values (gen_random_uuid(), %s, %s)",
            (owner_id, "dupe"),
        )

        with pytest.raises(ask_smoke.SetupError, match="corpus is split"):
            ask_smoke._resolve_class(conn, owner_id, "dupe")


class TestSetupValidityGuards:
    """Both guards answer one question: is this run SCOREABLE at all?"""

    def test_missing_expected_file_is_refused(self):
        """A file the corpus lacks scores as a MISS on every question citing it - an
        honest-looking 0% recall that is really a missing file."""
        questions = [question("q001", "answer", [("absent.pdf", 1)])]

        with pytest.raises(ask_smoke.SetupError, match="not ingested"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3})

    def test_in_corpus_question_without_sources_is_refused(self):
        """The silent-denominator hole: `retrieval_hit([], ...)` returns None, `compute_metrics`
        drops None rows, and the file-existence loop iterates SOURCES - so a sourceless answer row
        left the recall denominator with no warning at all, inflating the hit rate."""
        questions = [question("q009", "answer", [])]

        with pytest.raises(ask_smoke.SetupError, match="no 'expected_sources'"):
            ask_smoke._require_expected_files(questions, {"present.pdf": 3})

    def test_refuse_rows_are_allowed_to_have_no_sources(self):
        """The same emptiness is CORRECT out-of-corpus - `expected_sources` is in-corpus only
        (ADR 0021 §3). The guard must not confuse the two."""
        questions = [
            question("q001", "answer", [("present.pdf", 1)]),
            question("q010", "refuse", []),
        ]

        ask_smoke._require_expected_files(questions, {"present.pdf": 3})  # must not raise


class TestExitGate:
    """Issue #8's acceptance criterion, read minimally: >=1 GROUNDED, >=1 REFUSAL."""

    @staticmethod
    def _metrics(records):
        from gct.eval.scoring import compute_metrics

        return compute_metrics(records)

    def test_passes_with_one_of_each(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is True

    def test_fails_without_a_grounded_answer(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.REFUSAL, hit=True),
            EvalRecord("refuse", GrounderState.REFUSAL),
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_fails_without_an_honest_refusal(self):
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [
            EvalRecord("answer", GrounderState.GROUNDED, hit=True),
            EvalRecord("refuse", GrounderState.GROUNDED),  # hallucinated
        ]

        assert ask_smoke._print_gate(records, self._metrics(records)) is False

    def test_gate_line_splits_grounded_from_partial(self, capsys):
        """A run of 1 GROUNDED + 7 PARTIAL printing a bare "8/8" above "PASS" is literally
        accurate and completely misleading - PARTIAL is the TRACKED bucket, explicitly not a pass
        (ADR 0023 §2/§5). The last line is what a human skims, so the split prints inline."""
        from gct.eval.scoring import EvalRecord
        from gct.grounder.answer import GrounderState

        records = [EvalRecord("answer", GrounderState.GROUNDED, hit=True)] + [
            EvalRecord("answer", GrounderState.PARTIAL, hit=True) for _ in range(7)
        ] + [EvalRecord("refuse", GrounderState.REFUSAL)]

        ask_smoke._print_gate(records, self._metrics(records))
        out = capsys.readouterr().out

        assert "8/8" in out
        assert "1 GROUNDED + 7 PARTIAL" in out


class TestArgValidation:
    def test_k_below_one_exits_two_before_any_work(self, monkeypatch):
        """`--k 0` must die at parse time. Unvalidated it reached `retrieve()` mid-loop - AFTER
        the corpus was paid for - and exited 1, the code documented as "the gate failed"."""
        monkeypatch.setattr("sys.argv", ["ask_smoke.py", "--k", "0"])

        with pytest.raises(SystemExit) as exc:
            ask_smoke._parse_args()

        assert exc.value.code == ask_smoke.EXIT_SETUP

    def test_default_k_is_the_retrievers_own(self, monkeypatch):
        from gct.retriever.retrieve import DEFAULT_K

        monkeypatch.setattr("sys.argv", ["ask_smoke.py"])

        assert ask_smoke._parse_args().k == DEFAULT_K
